### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by Ralphkay** [algolia/angular-instantsearch#101]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: -- PLEASE FILL IN HERE --
Please, how do you customize the search box widget, for say, ionic searchbar? Thank you.

**Comment by iam4x** [comment]
Hi @Ralphkay,

You can use CSS to customize the look and feel but if you need to integrate the widget into a CSS framework you should create a custom widget for it.

There's a guide explaining how to do this here: https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html
