### ISSUE TITLE
Pagination buttons not disabled

### ISSUE THREAD

**Issue by stychu** [algolia/angular-instantsearch#102]
I'm not sure if its bug or my setup of the project affects this but when I have a small number of items for instant search the pagination buttons shows cursor to be disabled but actual buttons are clickable which I think is not intentioned.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9383657/37868888-7682a288-2fae-11e8-8eae-216d5a6544e5.gif)

**Comment by iam4x** [comment]
Hi @stychu thank you for pointing out the issue, this is definitely a bug.

**Comment by iam4x** [comment]
Hi this should be fixed with v1.0.2, can you confirm please @stychu ?

**Comment by stychu** [comment]
@iam4x Yes it's working properly now as of v1.0.2
