### ISSUE TITLE
Filter Search

### ISSUE THREAD

**Issue by stychu** [algolia/angular-instantsearch#103]
I dont understand how can I achieve default filtering by some properties in my index.

My data looks like this

```
{
  abc: {
    title: 'dsfew',
    country: 'ABC'
  },
  xyz: {
    title: 'aoskdoa',
    country: 'ASDOWQ'
  },
  ksa: {
    title: 'sdf546',
    country: 'OIDSKFE'
  },
}
```

What I would like to get is that on page view number 1 I want only to display records that contain in the country value for ex. country === 'ABC', and on the page  view number 2 I want everything but not including country === 'ABC'.

this is working only for 1 view and I know its bad approach...
` <ng-ais-refinement-list class="ais-RefinementList-item--selected hide-elem" attribute="polish.country"></ng-ais-refinement-list>`

**Comment by iam4x** [comment]
Hi @stychu,

This is a very special use case, not sure what do you to achieve in the end?
With having such a special UI/UX might not be the best fit to use angular-instantsearch, but maybe something lower level like https://github.com/algolia/algoliasearch-helper-js will help you to build your interface.

Please drop an email to support@algolia.com so we can discuss your use case.
