### ISSUE TITLE
How to use geofilter using angular-instantsearch

### ISSUE THREAD

**Issue by faraazc** [algolia/angular-instantsearch#108]
The Doc does not describe a way to query using lat lng using angular-instantsearch, wondering if this is supported. I have records in index with _geodoc set.

i want to restrict my search within certain radius and location

thanks

**Comment by vvo** [comment]
Hi @faraazc, you want to instantiate an Angular InstantSearch app with some geo filter applied. Do you also want to be able to update those geo filters?

Can you walk us a bit through what would be your geo search UI?

For now you can have a look at:
- The `InstantSearch` documentation: https://community.algolia.com/angular-instantsearch/widgets/instantsearch.html. You can pass a `config` object that can contain:

```js
    <ng-ais-instantsearch
      [config]="{
        apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
        appId: 'latency',
        indexName: 'instant_search',
		searchParams: {}
      }"
    >
  </ng-ais-instantsearch>
```

Inside searchParams, you can pass any search parameters including the geo ones: https://www.algolia.com/doc/guides/searching/geo-search.

- The customize widget part: https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html. You could create a custom widget that would refine your search based on some geo params. You can re-use the connectGeoSearch from InstantSearch.js and plug it in here: https://community.algolia.com/instantsearch.js/v2/connectors/connectGeoSearch.html

Let us know what you think.

This definitely requires a guide though. Thanks!

**Comment by faraazc** [comment]
Thanks @vvo .You have answered my query..The docs you prescribed has an answer. now i can instantiate angular instant search with geo points using config..

However it would be great if there is a way through api or through angular bindings to update or change the config specially geo points .Anyways for now my requirement is satisfied..Thanks for the support and thanks for responding to my query

**Comment by vvo** [comment]
> However it would be great if there is a way through api or through angular bindings to update or change the config specially geo points

Yes this is incoming via a dedicated Configure widget where you'll be able to update props and it will re-render your tree.

**Comment by yonathan06** [comment]
> Hi @faraazc, you want to instantiate an Angular InstantSearch app with some geo filter applied. Do you also want to be able to update those geo filters?
> 
> Can you walk us a bit through what would be your geo search UI?
> 
> For now you can have a look at:
> 
> * The `InstantSearch` documentation: https://community.algolia.com/angular-instantsearch/widgets/instantsearch.html. You can pass a `config` object that can contain:
> 
> ```
>     <ng-ais-instantsearch
>       [config]="{
>         apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
>         appId: 'latency',
>         indexName: 'instant_search',
> 		searchParams: {}
>       }"
>     >
>   </ng-ais-instantsearch>
> ```
> 
> Inside searchParams, you can pass any search parameters including the geo ones: https://www.algolia.com/doc/guides/searching/geo-search.
> 
> * The customize widget part: https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html. You could create a custom widget that would refine your search based on some geo params. You can re-use the connectGeoSearch from InstantSearch.js and plug it in here: https://community.algolia.com/instantsearch.js/v2/connectors/connectGeoSearch.html
> 
> Let us know what you think.
> 
> This definitely requires a guide though. Thanks!

After a little struggle with understanding why it doesn't work for me, figured out you changed it to `searchParameters`, instead of `searchParams`. Other then that it works great :)

**Comment by Haroenv** [comment]
Note that the more future-proof way of doing this now is using `configure`: https://community.algolia.com/angular-instantsearch/widgets/configure.html#configure
