### ISSUE TITLE
Query in searchParams

### ISSUE THREAD

**Issue by stychu** [algolia/angular-instantsearch#110]
In the previous version, I was able to do a query in `config.searchParameters` like so

```
searchParameters: {
        facets: ['XYZ'],
        facetsRefinements: isInCountry ? countryFacet : {} ,
        query: 'ABRAKADABRA',
        facetsExcludes: !isInCountry ? countryFacet : {}
      }
```

So when I entered a view with my search component I got `ABRAKADABRA` automatically in the search input. But now it seems not to work as before. Like the query isint added. But when I pass an array to the query like `searchParameters.query = ['ABRAKADABRA']` i can see it again in the input but there is an error and search crashes.

![image](https://user-images.githubusercontent.com/9383657/39178876-1f23c69e-47b3-11e8-8c89-f4784f04de33.png)

How can I get it working again ??

**Comment by Haroenv** [comment]
Hey @stychu, the query should be a string, it works as expected when I tried out an example: https://codesandbox.io/s/kov9o56zw7 (for example type `fire` after the prefilled query)

Can you share for an example in which this doesn't work?

**Comment by stychu** [comment]
I did find that when I change `urlSync` to `routing` it's not working. But when it's `urlSync` it works as expected but then I get a query string in the URL and also warning in the console about a depreciation of `urlSync`. But it works with urlSync so I will stick for now with this.

**Comment by Haroenv** [comment]
Interesting, does that happen with my example too? Cc @bobylito

**Comment by stychu** [comment]
@Haroenv in your example it looks like this variable is not even taken into the account for the search. Im not sure.

**Comment by samouss** [comment]
There is recent fix that has been released about InstantSearch about initial `searchParameters` being ignored by `routing`. The release of the patch has been released with the version [`2.7.2`](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#272-2018-04-18) of InstantSearch. Could you check with version of InstantSearch is used by Angular InstantSearch in your application?

**Comment by Haroenv** [comment]
Can you run:

```sh
npm install instantsearch.js@^2.7.2
```

to force the newer version @stychu ?

**Comment by iam4x** [comment]
What version of InstantSearch.js is installed with Angular InstantSearch @stychu ?

You can find out with: `$ cat node_modules/instantsearch.js/package.json | grep version`

This should be solved with a `yarn upgrade` or `npm update`

**Comment by iam4x** [comment]
I'm closing this issue since there's no answer from @stychu.

Feel free to open a new issue.
