### ISSUE TITLE
Documentation transformItems

### ISSUE THREAD

**Issue by aymericaitamer** [algolia/angular-instantsearch#114]
Hi Algolia,

You added transformItems on refinement list : https://github.com/algolia/angular-instantsearch/commit/9b7a007

But there is no documentation about it : https://community.algolia.com/angular-instantsearch/widgets/refinement-list.html

I try to do this :
```
<ng-ais-refinement-list attribute="category" [sortBy]="['name','desc']" showMoreLabel="See more" showLessLabel="See less"
            [limit]="3" [showMoreLimit]="100" [transformItems]="translate(items)"></ng-ais-refinement-list>

```
=> translate function is invoked but items is undefined. Do you have a demo with transformItems  that works ?

NB : To understand my need, i have to translate item facets.

**Comment by Haroenv** [comment]
Hey @aymericaitamer, 

The function should not be called, but rather passed as reference. Like this:

```html
<ng-ais-refinement-list attribute="category" [sortBy]="['name','desc']" showMoreLabel="See more" showLessLabel="See less"
            [limit]="3" [showMoreLimit]="100" [transformItems]="translate"></ng-ais-refinement-list>
```

However, note that the function should change the `highlighted` value for it to show in the default template. Like this:

```ts
import { Component } from '@angular/core';

const translationTable = {
  Apple: 'pomme',
};

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'app';
  translate(items) {
    return items.map(item => ({
      ...item,
      label: translationTable[item.label] || item.label, // not displayed
      highlighted: translationTable[item.highlighted] || item.highlighted, // the displayed one
    }));
  }
}
```

**Comment by aymericaitamer** [comment]
Works like a charm. Thank you a lot !

**Comment by robert-king** [comment]
thanks a lot! worth adding to documentation IMO, I mistakenly had a translate method that only mapped a single item, and also my service was undefined inside the translate function because it wasn't bound  / binded properly.

needed this solution:

```
translate = (items) => {
    return this.propertyService.toPropertyContainers(items);
  }
```

**Comment by Haroenv** [comment]
Where in the documentation would you have looked for this? Just checking so we can document it in the right place @robert-king

**Comment by robert-king** [comment]
https://community.algolia.com/angular-instantsearch/widgets/hits.html
