### ISSUE TITLE
CSS from instantsearch.js missing in v2.0.0

### ISSUE THREAD

**Issue by guillaume-ro-fr** [algolia/angular-instantsearch#123]
In the 2.0.0 version, we don't have the `node_modules/angular-instantsearch/bundles/` folder, so we can't include the CSS files in the `angular.json` config file.

Maybe the [`angular-instantsearch/scripts/build.sh`](https://github.com/algolia/angular-instantsearch/blob/master/scripts/build.sh) script was not executed (cc @iam4x) ? 😉

**Comment by Haroenv** [comment]
Css should be in the “instantsearch.css” package right?

**Comment by guillaume-ro-fr** [comment]
Yes, but in the v1.0.2, and according to the [current documentation](https://community.algolia.com/angular-instantsearch/getting-started.html#import-module) and the `build.sh` script, you need to use the CSS files from this package.

**Comment by iam4x** [comment]
@guillaume-ro-fr I'm investigating 🧐

@Haroenv The build process should copy the css and distribute it from the angular-instantsearch package. This was done because `instantsearch.css` is not including every styles for angular-instantearch (ex: range-slider)

**Comment by iam4x** [comment]
v2.0.1 is released with the correct dist folder https://cdn.jsdelivr.net/npm/angular-instantsearch@2.0.1/bundles/ there is now the CSS 👍 

(This was a mistake from moving the `ng-packagr` build process)
