### ISSUE TITLE
Infinite hits show more button is not displayed

### ISSUE THREAD

**Issue by kyleabens** [algolia/angular-instantsearch#126]
I'm currently implementing angular instant search components in my ionic app and noticed that there is no show more button in ais-infinite-hits component.  I tried changing the showMoreLabel attribute but still nothing.  My search box and list of hits works just fine, I just can't retrieve the next set of results.  Is there a way for me to trigger the next set of results?  I'm hoping I can get an example of what the show more function is doing so I can add it to my infinite scrolling directive.

Thanks!

```
<ais-instantsearch [config]="searchConfig">

    <ais-search-box></ais-search-box>

    <ais-infinite-hits showMoreLabel="hello world">

      <ng-template let-hits="hits" let-results="results" let-showMore="showMore">

          <div *ngIf="hits.length === 0">
            No results found.
          </div>

        <ion-list>
          <ion-item *ngFor="let hit of hits">{{ hit.Make_Name }}</ion-item>
        </ion-list>

      </ng-template>

    </ais-infinite-hits>

  </ais-instantsearch>
```

**Comment by samouss** [comment]
By providing a custom template to the `ais-infinite-hits` component the button is not rendered anymore. You have to reimplement it along with the hits. Here is [an example](https://codesandbox.io/s/8y9lzxv192) that shows how to implement it.
