### ISSUE TITLE
List the class available for each widgets

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#127]
Like we do in the other flavours it would be nice to have the list of all the class available.

> https://community.algolia.com/react-instantsearch/widgets/Highlight.html#classnames
> https://community.algolia.com/vue-instantsearch/components/highlight.html#css-classes

**Comment by Haroenv** [comment]
(until we document this, just a small note:)

all css classes used should be identical to React InstantSearch, as well as identical DOM output.

**Comment by onewiseburdman** [comment]
What about Angular?  I've been trying to find the information on how to change the widget css class.  IE SearchBox.  I want to apply my own CSS, do I have to create custom widgets to do this?  Or turn off the magnifier as an example.  I don't mind doing so, but it seems contrary to the overall flow of things.

**Comment by samouss** [comment]
You can't change the CSS classes of the widget in Angular InstantSearch. To do so you'll need to extend the widget to write your own version of the DOM. You can take a look at [this guide](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html) in the documentation that explains how to customise a widget.

**Comment by mceris** [comment]
Is there any way to override the css (not change the classes)?  My search page without touching the css looks like this:

<img width="194" alt="screen shot 2018-07-22 at 10 03 58 pm" src="https://user-images.githubusercontent.com/34826352/43053548-4aecfe38-8dfb-11e8-93ba-5e47621bd0cd.png">

**Comment by onewiseburdman** [comment]
No - you cannot override the class without creating a component a custom component.  However - it was really, really easy to do so.  Complete Component  `import { Component,
  Inject, forwardRef,
  OnInit  } from '@angular/core';
import { BaseWidget, NgAisInstantSearch } from 'angular-instantsearch';
import { connectSearchBox } from 'instantsearch.js/es/connectors';

@Component({
  selector: 'searchbox',
  template: '<input placeholder="Enter Zip Code Here" class="input" type="search" (input)="state.refine($event.target.value)">',
  styleUrls: ['./searchbox.component.css']
})
  export class SearchboxComponent extends BaseWidget {
  
    constructor(
      @Inject(forwardRef(() => NgAisInstantSearch))
      public instantSearchParent
    ) 
    {
      super('SearchBox');
    }
    public ngOnInit() {
      this.createWidget(connectSearchBox);
      super.ngOnInit();
    }
    
  }
  `

**Comment by onewiseburdman** [comment]
`.input{
    height: 25px;
    line-height:22px;
    background-color: #f2f2f2;
    border: 0;
    font-weight: 300;
    font-style: inherit;
    color: #222222;
    font-size: 22px;
    padding: 25px;
    text-align: center;

    border: 1px solid #f2f2f2;

}
.input{
    height: 25px;
    line-height:22px;
    background: transparent;
    border-radius: 5px 5px 5px 5px;
    padding: 25px;
    position: relative;

}


.input:focus{
    height: 25px;
    line-height:22px;
    border: 1px solid #1caad3;

}`
css

**Comment by onewiseburdman** [comment]
what the import into my other component looked like.  
`					<app-searchbox (change)=searchChanged($event.target.value)></app-searchbox404>
`

**Comment by tkrugg** [comment]
We decided to provide this as it turns out not to be so useful.
it seems like providing a way to rename/add CSS classes  is  definitely useful.
https://github.com/algolia/angular-instantsearch/issues/127#issuecomment-403503548
This is something we're thinking of adding in the future.

Closing this for now.
