### ISSUE TITLE
use algoliasearch/lite

### ISSUE THREAD

**Issue by Haroenv** [algolia/angular-instantsearch#136]
This is available on TypeScript (DefinitelyTyped) now, so it should work. I think we can also change it to 

```ts
import algoliasearch from 'algoliasearch/lite';
```

rather than the * import.

see:

https://github.com/algolia/angular-instantsearch/blob/faf717c2372e6e2d1d50d38f25783d9db322bffb/src/instantsearch/instantsearch.ts#L14

and 

https://github.com/algolia/angular-instantsearch/blob/faf717c2372e6e2d1d50d38f25783d9db322bffb/src/instantsearch/instantsearch.ts#L20

cc @samouss @vvo

**Comment by samouss** [comment]
We can probably get rid of `import *` with the compiler setting [`allowSyntheticDefaultImports`](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by vvo** [comment]
Tried it and did not work, what you can do is const mod = require("som/mod");

works 100%
