### ISSUE TITLE
connectSearchBox

### ISSUE THREAD

**Issue by onewiseburdman** [algolia/angular-instantsearch#183]
I'm using connect search box but it doesn't seem to work at all.  I'm using Angular 6, if I use 
ais-search-box component

 no issues.  I created a component and import the component no issues, could someone please help me out here?

``` ts
import { Component, Inject, forwardRef, OnInit } from "@angular/core";
import { BaseWidget, NgAisInstantSearch } from "angular-instantsearch";
import { connectSearchBox } from "instantsearch.js/es/connectors";

@Component({
  selector: "app-searchbox",
  templateUrl: "./searchbox.component.html",
  styleUrls: ["./searchbox.component.css"]
})
export class SearchboxComponent extends BaseWidget implements OnInit {
  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchParent
  ) {
    super("SearchBox");
  }
  public ngOnInit() {
    this.createWidget(connectSearchBox, { searchAsYouType: "true" });
    super.ngOnInit();
  }
}
```

**Comment by francoischalifour** [comment]
Hi there,

What does your `searchbox.component.html` look like?

Here is a working example with an inline template. Note that I use the `refine()` function on the `input` event attached to my `input` element.

```javascript
import { Component, Inject, forwardRef, OnInit } from "@angular/core";
import { BaseWidget, NgAisInstantSearch } from "angular-instantsearch";
import { connectSearchBox } from "instantsearch.js/es/connectors";

@Component({
  selector: "app-searchbox",
  template: '<input type="search" (input)="state.refine($event.target.value)">'
})
export class SearchboxComponent extends BaseWidget {
  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchParent
  ) {
    super("SearchBox");
  }

  public ngOnInit() {
    this.createWidget(connectSearchBox);
    super.ngOnInit();
  }
}
```

Let me know if that helps!

**Comment by francoischalifour** [comment]
You can find the working example on [this sandbox](https://codesandbox.io/s/xjozrwz7z4).

Please explain what doesn't work for you.

**Comment by onewiseburdman** [comment]
This is what I was missing - something silly, I supposed.  Nonetheless - it got it working, and you sent me down the right path.  
On the imported component I added this:
`(change)=searchChanged($event.target.value)`
On the component it was imported too:
`
  searchChanged(query) {
    if (query.length) {
      this.showResults = true;
    } else {
      this.showResults = false;
    }`
 Thank you so much for your help.  It really is pretty simple to get this working.  I feel like the documentation is lacking in some basic steps.  However over time, as people like me keep hacking away to get things working like we want - those answers will be derived.  Your help has been greatly appreciated, I can't state that enough.  You can take a mic drop for that.
