### ISSUE TITLE
refresh() method does not exist in 'InstantSearchInstance'

### ISSUE THREAD

**Issue by tahmina8765** [algolia/angular-instantsearch#185]
To clear the cache and update search result, refresh() method is already implemented in instantsearch.js.

https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-refresh

But in this library, it is missing. https://github.com/algolia/angular-instantsearch/blob/develop/src/instantsearch/instantsearch.ts#L187

**Comment by Haroenv** [comment]
Yes, seems like that method wasn't correctly aliased from the main InstantSearch.js

**Comment by Haroenv** [comment]
I just added it, will release soon https://deploy-preview-186--angular-instantsearch.netlify.com/examples/dev-novel/?selectedStory=Custom%20widgets.Refresh
