### ISSUE TITLE
Typo in the doc

### ISSUE THREAD

**Issue by mparpaillon** [algolia/angular-instantsearch#187]
Hi, thanks for this package
I've spotted a typo here: https://community.algolia.com/angular-instantsearch/widgets/stats.html

It should be
```js
@Component({
  selector: 'my-app',
  template: `
    <ais-stats>
      <ng-template let-state="state">
        {{state.nbHits}} results found in {{state.processingTimeMS}}ms.
      </ng-template>
    </ais-stats>
  `
})
export class AppComponent {}
```

**Comment by Haroenv** [comment]
thanks, see https://github.com/algolia/angular-instantsearch/pull/188 (in the future you could make the PR yourself, there's an edit button at the top of the page 😊)
