### ISSUE TITLE
Autofocus Option for ais-search-box

### ISSUE THREAD

**Issue by sandiphob** [algolia/angular-instantsearch#208]
Could an autofocus option be added for ais-search-box?

**Comment by Haroenv** [comment]
Sorry for missing this; yes autofocus should be an option for search-box. Do you want to contribute and add it?

**Comment by kedar9444** [comment]
is this in place or still  waiting for contributor ?

**Comment by Haroenv** [comment]
Hasn’t been added so far :)

**Comment by kedar9444** [comment]
I have done it., adding PR request for the same.

**Comment by Haroenv** [comment]
Sorry, you made that PR during the weekend, when I don't work :)

**Comment by tkrugg** [comment]
fixed by https://github.com/algolia/angular-instantsearch/pull/297
