### ISSUE TITLE
Move from DevNovel to Storybook

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#226]
Move our showcase from [DevNovel](https://github.com/algolia/dev-novel) to [Storybook](https://storybook.js.org/basics/guide-angular/) to leverage the community & plugins of Storybook. It also brings consistency across our different flavours since React & Vue are already on Storybook. 

Related https://github.com/algolia/instantsearch.js/issues/3051

**Comment by tkrugg** [comment]
Action plan:
- [x] set up initial boilerplate for storybook #368 
- [x] set build for storybook #368 
- [ ] migrate dev-novel examples under storybook
- [ ] delete dev-novel
