### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by astr0sl0th** [algolia/angular-instantsearch#227]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is:

I am still a little unclear about how to build a custom widget or extend one of the base widgets? We have have the components made for refinement I now need to make the logic work for our particular use case.

Here is something alone the lines of what we want to achieve:

![screen shot 2018-08-08 at 09 46 48](https://user-images.githubusercontent.com/9317246/43826854-46c7b1b6-9af0-11e8-934a-5118cdc4caef.jpg)

As you can see they are kind of similar to the pre-build ones with a few exceptions. How would you recommend I build these?

**Comment by samouss** [comment]
To implement those kind of UI most of the time we recommend to customize widgets rather than only rely on classNames. There is a guide about that [in our documentation](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html). It will show you how to build a [Menu](https://community.algolia.com/angular-instantsearch/examples/dev-novel/?selectedStory=Menu.default) with a select element. You can basically apply this guide to your Category widget since it looks like the behaviour is the same as the Menu (can only refine one value at the time). Then you can decline your learnings to the two others. Don't hesitate to ask question!

**Comment by astr0sl0th** [comment]
Fixed, I was calling the wrong function for search. Should of been `searchForItems: () => void;`

**Comment by astr0sl0th** [comment]
Fixed, I was calling the wrong function for search. Should of been `searchForItems: () => void;`

**Comment by samouss** [comment]
I looked at your code indeed that was the issue. You can find your example updated below. Don't hesitate to take a look at [the implementations](https://github.com/algolia/angular-instantsearch/tree/develop/src) of the built-in widgets.

```ts
import { Component, Inject, forwardRef, OnInit } from '@angular/core';
import { BaseWidget, NgAisInstantSearch } from 'angular-instantsearch';
import { connectRefinementList } from 'instantsearch.js/es/connectors';

@Component({
  selector: 'app-brand-refinement-list',
  template: `
    <div class="catalogue__filters__group">
        <div class="catalogue__filters__quickSearch">
          <div class="field field--search">
            <input
              type="text"
              class="field__input"
              placeholder="Search"
              (input)="state.searchForItems($event.target.value)"
            />
          </div>
        </div>

        <ul class="catalogue__filters__list">
          <li
            *ngFor="let item of state.items"
            [ngStyle]="{ fontWeight: item.isRefined ? 600 : 400 }"
          >
            <a href="#" (click)="state.refine(item.value)">
              <span>{{ item.label }}</span>
              <span class="catalogue__filters__list__item__qty">({{item.count}})</span>
            </a>
          </li>
        </ul>
    </div>
  `,
})
export class BrandWidgetComponent extends BaseWidget implements OnInit {
  state: {
    items: { label: string; value: string }[];
    createURL: () => string;
    refine: (value: string) => void;
    searchForItemsfunction: () => void;
    isFromSearchboolean: boolean;
    canRefine: boolean;
    canToggleShowMore: boolean;
    isShowingMore: boolean;
    toggleShowMore: () => void;
  };

  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch)) public instantSearchParent
  ) {
    super('AisBrandWidgetComponent');
  }

  public ngOnInit() {
    this.createWidget(connectRefinementList, { attributeName: 'brand' });
    super.ngOnInit();
  }
}
```
