### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by jayankaghosh** [algolia/angular-instantsearch#234]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: 
How to add a numericFilter to my search index

I am using the ais-instantsearch component of Algolia to search and show results, in Angular.

Currently, this is my code,

    <ais-instantsearch [config]="config">
        <ais-hits>
            ...
        </ais-hits>
    </ais-instantsearch>

Now my question is, how to add numericFilter to this search request?

For example, I want to return all hits with attribute `is_simple=1`. How to achieve that?

**Comment by samouss** [comment]
You can use the [Configure](https://community.algolia.com/angular-instantsearch/widgets/configure.html) widget to provide such parameters. Here is [an example](https://codesandbox.io/s/lq16p36vl). Algolia will only return results that has the attribute `free_shipping` to `true`. Here is how to setup the `Configure` widget for this:

```html
<ais-configure [searchParameters]="{ filters: 'free_shipping:true' }"></ais-configure>
```
