### ISSUE TITLE
Angular 6 and SSR

### ISSUE THREAD

**Issue by corentin-gautier** [algolia/angular-instantsearch#235]
Hi, 

I'm trying to use instantsearch on a project which requires angular 6 but I'm having two issues:

1. After the build the npm run serve:ssr returns: 
```shell
import algoliasearchHelper from 'algoliasearch-helper';
SyntaxError: Unexpected token import
```

2. The final step from https://community.algolia.com/angular-instantsearch/guides/server-side-rendering.html) throws an error on client side:

ERROR Error: 
Usage: instantsearch({
  appId: 'my_application_id',
  apiKey: 'my_search_api_key',
  indexName: 'my_index_name'
});

Are those compatibility issues with angular 6 ? If it is, do you have an ETA on v6 compatibility ?

Thanks !

**Comment by Haroenv** [comment]
would it be possible to leave the code that results in that SSR error in a GitHub repository we can investigate?

**Comment by corentin-gautier** [comment]
@Haroenv you should see both issues here : https://github.com/corentin-gautier/angular6-ssr-algolia

It's a basis ng new, ng generate universal then folliwing the SSR tutorial from your documentation

**Comment by Haroenv** [comment]
Thanks for that reproduction, it will help in debugging the issue. In the meantime, is that with the specific commit of angular universal?

**Comment by corentin-gautier** [comment]
I've used angular-cli 6.1.3, which seems to use angular ^6.1.0 (in package.json)

**Comment by corentin-gautier** [comment]
Hey @Haroenv ! Any update on this ? I'm currently working on a project that needs to be ready for mid-october-ish so I'm a little worried about not being able to build it :)

**Comment by Haroenv** [comment]
Sorry, no update on this yet, I'm currently working on something else, but I'll let the team know to see if someone could take a look at this

**Comment by francoischalifour** [comment]
Hey @corentin-gautier, I sent a PR to fix your issue: https://github.com/corentin-gautier/angular6-ssr-algolia/pull/1.

Our documentation is not up to date, sorry about that. We'll make sure to update it. `createSSRSearchClient` must be used with the `searchClient` property now.

Closing this issue. Feel free to reopen if you face any other problem!

**Comment by corentin-gautier** [comment]
@francoischalifour ok thanks ! this fixes the second issue. 

I'm still having the first issue though. I managed to build the project by using this trick on instantsearch.js : https://github.com/SebastianM/angular-google-maps/issues/1052#issuecomment-331150772

Looks like this is a recurring issue with angular librairies.

**Comment by corentin-gautier** [comment]
@francoischalifour hey, so update on this: I was using the latest commits from https://github.com/angular/universal-starter, but turns out they removed webpack from the build process in the last 2 commits. So rolling back to using webpack solves the issues with third party librairies.

For everyone having this issue just follow the guide here: https://github.com/angular/angular-cli/wiki/stories-universal-rendering#step-5-setup-a-webpack-config-to-handle-this-node-serverts-file-and-serve-your-application to add webpack on build (and make sure to roll back what they changed in the last 2 commits of the universal starter)

**Comment by francoischalifour** [comment]
Thank you for sharing, @corentin-gautier. We'll redirect users facing the same issue to this link, then!
