### ISSUE TITLE
release script fails if there's a commit in master which isn't in develop

### ISSUE THREAD

**Issue by Haroenv** [algolia/angular-instantsearch#236]
I had to merge myself, and push before doing the change, when a PR (#188) was merged in master instead of develop. 

The release script made a merge conflict and then threw an error without cleaning up again which made it complicated to fix my local setup

Unrelated I'm also wondering a bit why the script does `yarn cache clean`, does that have a reason?

**Comment by Haroenv** [comment]
We really should move to a common release script, that would fix these problems

**Comment by Haroenv** [comment]
Also the release script failed on `npm` since it doesn't pretend to be a TTY, so it doesn't ask for a OTP.
see https://github.com/algolia/instantsearch.js/pull/3053/ for the fix

**Comment by tkrugg** [comment]
Closing this as it is not particular to this repo but rather general.
