### ISSUE TITLE
attributesForFaceting

### ISSUE THREAD

**Issue by corentin-gautier** [algolia/angular-instantsearch#237]
Hi,

I'm trying to use a refinement list with searchable but getting the error 

```
Cannot search in `[MY_FIELD_NAME]` attribute, you need to add `searchable([MY_FIELD_NAME])` to attributesForFaceting.
```

There is no mention of attributesForFaceting in the [angular] documentation so I have no idea how to do that.

Thanks

**Comment by Haroenv** [comment]
Hey @corentin-gautier, you need to add that to the settings on the Algolia dashboard or via the API. It's in the "display" tab on "indices". 

Feel free to comment if you don't find it
