### ISSUE TITLE
I am not able to add filter in ionic

### ISSUE THREAD

**Issue by dileepxdn** [algolia/angular-instantsearch#244]
I want a filter that will get all values in the attribute area of my algolia document and fetch the result. But, this  ais-refinment-list  is not snowing anything all other are woking fine. please help me .
please see the code .

```html
<ais-instantsearch [config]="{
      apiKey: 'KEY',
      appId: 'ID',
      indexName: 'index',
      routing: true
    }">  

<ais-refinement-list attribute="area"></ais-refinement-list>

    <ais-search-box placeholder="Search"></ais-search-box>
  <ais-hits>
      <ng-template let-hits="hits">
              **** All HITS ***
      </ng-template>
   </ais-hits>
        <ais-pagination></ais-pagination>

  </ais-instantsearch>
```

**Comment by Haroenv** [comment]
I see one possible reason why this is happening, which could be that you didn't set up the attribute `area` as `attributesForFaceting` in the dashboard or the API. 

If that is correct, you should see an error message in the console. Do you see any of those?

**Comment by dileepxdn** [comment]
I haven’t seen any error bro.

**Comment by Haroenv** [comment]
you're welcome!
