### ISSUE TITLE
Return value from searchForFacetValues is an array not an object

### ISSUE THREAD

**Issue by corentin-gautier** [algolia/angular-instantsearch#249]
in instantsearch.d.ts:

``` typescript
export declare type SearchClient = {
    search: (requests: SearchRequest[]) => Promise<{
        results: SearchResponse[];
    }>;
    searchForFacetValues?: (requests: SearchForFacetValuesRequest[]) => Promise<{
        facetHits: SearchForFacetValuesResponse[];
    }>;
};
```

The return type of the searchForFacetValues request is an **array** of object containing facetHits instead of an object containing facetHits

**Comment by corentin-gautier** [comment]
here : https://github.com/algolia/angular-instantsearch/blob/bbaabbf035dd9821514af143eb91b6c4d27f4932/src/instantsearch/instantsearch.ts#L152

**Comment by francoischalifour** [comment]
Thank you @corentin-gautier!
