### ISSUE TITLE
Unit and number format on Range Slider

### ISSUE THREAD

**Issue by corentin-gautier** [algolia/angular-instantsearch#251]
Hi,

Didn't find anything about adding a custom unit to the range slider tooltips (like €, or Km) also would be nice to be able to format using the number pipe (to display "1 254" instead of "1254")

**Comment by Haroenv** [comment]
utils is available here: https://github.com/algolia/angular-instantsearch/blob/develop/src/utils.ts if it's not exported, you should be able to copy-paste what you need into your own code

**Comment by corentin-gautier** [comment]
@Haroenv oh yeah ... don't know why I didn't thought of that ! Thanks for the support !
