### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by jeanpfs** [algolia/angular-instantsearch#256]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: 
Showcase link for [Custom Widget](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html).

**Comment by francoischalifour** [comment]
Indeed, the link should be: https://community.algolia.com/angular-instantsearch/examples/dev-novel/?selectedStory=Custom%20widgets.MenuSelect

Thank you for noticing, I will fix that!
