### ISSUE TITLE
Uncaught Error: Template parse errors: Can't bind to 'config' since it isn't a known property of 'ais-instantsearch' in e-commerce example

### ISSUE THREAD

**Issue by omnecon** [algolia/angular-instantsearch#258]
I am trying to getting the e-commerce example to work. However I am running in the exception:

Uncaught Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ais-instantsearch'

From my point of view, the module is imported correctly with NgAisModule.forRoot() in AppModule. What else might be wrong in the example?

My node version is v10.10.0 and I have tried it on Ubuntu and on Windows, always with the same result. Thanks for any hints.

**Comment by Haroenv** [comment]
Do you have these errors as well on codesandbox? 

https://codesandbox.io/s/github/algolia/angular-instantsearch/tree/develop/examples/e-commerce

I'm not seeing any errors there, but maybe you might have a different error message there?

**Comment by omnecon** [comment]
on codesandbox there is this error, which is another one I have in my local env:
![image](https://user-images.githubusercontent.com/2782032/45876164-2816db80-bd9a-11e8-9619-cb8cb664437d.png)

**Comment by omnecon** [comment]
I could fix the issue now.

I upgraded the dependency 'angular-instantsearch' from 1.0.1 to 2.0.4 and removed dependency 'instantsearch.js' totally.

Please update the example in GIT, if you think this solution is appropriate. I will close this ticket! Thx!

**Comment by Haroenv** [comment]
Wow, you're right! I didn't see that the wrong version was linked there. Sorry for not noticing that earlier. Will fix it!
