### ISSUE TITLE
Reseting search and filtering on new facet/query

### ISSUE THREAD

**Issue by corentin-gautier** [algolia/angular-instantsearch#281]
Hi,

Is there currently a way to reset then search for a specific facet or query without doing multiple requests ?

I'm working on an app that has external components that trigger either a query or a facet search. The way I'm handling it right now is:
- resetting the facets by calling the NgAisClearRefinements state.refine()
- resetting the search box by calling NgAisSearchBox handleChange('')
- setting the new facet value by calling NgAisRefinementList state.refine(value)

OR
- resetting the facets by calling the NgAisClearRefinements state.refine()
- setting the query by calling NgAisSearchBox.handleChange(value)

This is very inefficient as it'll make several requests to the algolia API.

I've tried using the SearchRequestParameters directly by using the configure widget but widgets don't update when doing that.

**Comment by samouss** [comment]
Hi @corentin-gautier, Angular InstantSearch is really widgets oriented. It means that each of them is responsible for managing its own part of the state. Basically what you want to do is to bypass the widget lifecycle and manipulate the state directly right? It should be possible with the `configure` widget.

Is it possible to have an example of what you have implemented? It will help us to better understand the context. Here is [a template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch) for Angular InstantSearch.

**Comment by corentin-gautier** [comment]
Hi, 
I can't really show you what I've implemented but using the template you've linked : just imagine you have an ad on the page saying samsung products are on sale with a button saying "show all samsung products". This button would do the same action as a user manually reseting the facets then selecting the samsung facet value. How would you do something like that ? (keeping in mind that it means resetting any other values in other facets like price range or something else and also resetting the search box)

I know it's kinf of an advanced use case, and my code currently works I'm just wondering if I can do this in a better way :)

**Comment by Haroenv** [comment]
So since it's kind of advanced, you'll need to write your own connector. 

As described in the guide, you will

1. make a factory function as asked
2. in render method, call the clearRefinements things on a function you return, and also refine

For both those things, it comes down to making a combination of:

```
import { clearRefinements } from 'instantsearch.js/es/lib/utils';
const connectClearAndSet = (renderFn, unmountFn) => ({
  attribute,
  refinement,
  clearsQuery = true,
  excludedAttributes = [],
} = {}) => ({
  _cachedRefine: () => {},
  init() {
    renderFn({ refine: this._cachedRefine }, true);
  },

  render({ helper }) {
    this._cachedRefine = () => {
      helper
        .setState(
          clearRefinements({
            helper,
            excludedAttributes,
            clearsQuery,
          }),
        )
        .addFacetRefinement(attribute, refinement)
        .search();
    };
    renderFn(
      {
        refine: this._cachedRefine,
      },
      false,
    );
  },

  dispose() {
    unmountFn();
  },
});
```

Then you need to put `connectClearAndSet` as the connector for your custom widget, pass the attribute and refinement to widgetParams from the props of your custom component. Then you can call `refine` when someone clicks on the ad itself

**Comment by corentin-gautier** [comment]
@Haroenv thanks for the example, this seams to be what i'm looking for. However the connectClearAndSet is not a valid Connector and I don't quite understand why and how to make it work.

**Comment by Haroenv** [comment]
https://codesandbox.io/s/3y8yxyw5r1

**Comment by corentin-gautier** [comment]
@Haroenv thanks a lot for taking the time to write this example !
