### ISSUE TITLE
Angular2+ multiple indices integration

### ISSUE THREAD

**Issue by ankitverma31** [algolia/angular-instantsearch#282]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: Angular2+ multiple indices integration

**Comment by Haroenv** [comment]
There's no guide for this now; but https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html & https://community.algolia.com/instantsearch.js/v2/connectors/connectAutocomplete.html together should fix the solution

**Comment by tkrugg** [comment]
Duplicate of https://github.com/algolia/angular-instantsearch/issues/51
