### ISSUE TITLE
ng update to Angular 7 : "Cannot read property 'split' of null" likely related to angular-instantsearch package

### ISSUE THREAD

**Issue by wduville** [algolia/angular-instantsearch#320]
### Versions
* @angular/cli: 6.2.3 and 7.0.2, 7.0.3
* @angular/core : 6.1.10
* angular-instantsearch: "^2.0.4"
* OS: Windows 10 x64
* node: v8.11.2
* npm: 6.4.1

### Repro steps

With `@angular/core : 6.1.10`
Having `"angular-instantsearch": "^2.0.4"` under `"dependencies"` of `package.json`,
Run the command: `ng update @angular/core`

### The log given by the failure

Only got this one line:
**`Cannot read property 'split' of null`**

### Workaround

Temporarily remove `"angular-instantsearch": "^2.0.4"`  from `package.json`, allows the update to proceed. After the update, put it back and run `npm install`

**Comment by Haroenv** [comment]
Hey! Would it be possible to create a sandbox with the exact setup you have? It will be easier to get to the source of the bug.

**Comment by wduville** [comment]
Sure ! Attached.
[my-app_ng_update_@angular_core_fails.zip](https://github.com/algolia/angular-instantsearch/files/2514729/my-app_ng_update_.angular_core_fails.zip)

The repro steps are:
* `ng new my-app`
* add `"angular-instantsearch": "^2.0.4"` dependency in `package.json`,
* `ng update @angular/core` -> **Fail** with **`Cannot read property 'split' of null`**

PS: I edited the comment above with node (v8) and npm versions.
PS2: This bug has been reported here https://github.com/angular/angular-cli/issues/12644 as well

**Comment by tkrugg** [comment]
For anyone running into this issue, you can now update to [angular-instantsearch@2.1.0](https://github.com/algolia/angular-instantsearch/blob/develop/CHANGELOG.md#210-2018-10-31) before running `ng update`.
