### ISSUE TITLE
Would you please suggest Angular 7 compatible npm ?

### ISSUE THREAD

**Issue by RamuRChenchaiah** [algolia/angular-instantsearch#334]

**Comment by Haroenv** [comment]
You can use Angular InstantSearch 2.1.0, which is compatible with Angular 7. Please comment here if you have any more issues with it, with a reproducible example. We have a sandbox available: 

https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch
