### ISSUE TITLE
Issues with Angular-Instantsearch and AWS Amplify

### ISSUE THREAD

**Issue by Loghrenar** [algolia/angular-instantsearch#337]
Hello everyone, 

I'm currently working on an Angular (6.10) Application using multiples packages as `aws-amplify`, `angular-instantsearch`, etc.

I had a problem with uploading files to S3 buckets with `aws-amplify` (https://github.com/aws-amplify/amplify-js/issues/1109).

As I investigated further than just `aws-amplify` problems, I found that my bug appeared when I install  `angular-instantsearch` on my project and use the fix delivered in the documentation.
```
(window as any).process = {
  env: { DEBUG: undefined },
};
``` 
at the bottom of the `polyfills.ts` file.

`aws-amplify` have their own fix in `index.html`:
```
   var global = global || window;
   var Buffer = Buffer || [];
```

So, i'm here wondering is the fix from `angular-instantsearch` still needed or is there another fix which don't conflict, is the documentation up to date with latest Angular versions ?
Currently thinking a solution would be to switch from `aws-amplify` to `aws-sdk` or to switch from `angular-instantsearch` to `@types/algoliasearch`.

Thanks in advance for any suggestion, help, feedback about this bug.

**Comment by Haroenv** [comment]
wow that looks really odd, can you give a complete application which will give this error? Those two things seem unrelated to me

**Comment by Loghrenar** [comment]
Here @Haroenv,

So, i just recreated a stackblitz with all informations needed but a problem with a library (`zlib`) don't run the application which is strange because it's working when installing manually.

Here is the stackblitz: 
https://stackblitz.com/edit/angular-ph3t1e

Best way to run this project is to:

- download the project and go to folder.
- run `npm install` in the angular project.
- in `storage.service.ts` fill all the `xxx` fields with Cognito pools, bucket, etc (I can't give this type of informations in a Github issue)
- try to upload a `jpg` or `png` file with the input file on the page and check the console with errors

If i remove `angular-instantsearch` (which include the fix in `polyfills.ts`, everything is working fine.

**Comment by Loghrenar** [comment]
Hey @Haroenv,

Any update on this issue ?
Did you recreate the project correctly ?

**Comment by tkrugg** [comment]
Hi @Loghrenar: I haven't managed to follow this step:
> in storage.service.ts fill all the xxx fields with Cognito pools, bucket, etc (I can't give this type of informations in a Github issue) / ! \ You need to be logged in an existing pool matching the one in the storage part, you need to use cookies as the storage system
If creating this access free? If yes could you setup a disposable account I can use to reproduce this issue?

**Comment by Loghrenar** [comment]
Hey @tkrugg, 

I will try to make an access free example asap.

**Comment by Loghrenar** [comment]
I'm back @tkrugg,

I updated the project:
https://stackblitz.com/edit/angular-ph3t1e

You have a full login/logout/upload process, you can create a cognito pool and a S3 bucket with the AWS free trial to test it.
If you struggle, contact me personally for messages, planning a call.

**Comment by tkrugg** [comment]
Maybe the workaround we suggest is a little abusive.
I suspect the issues you're experiencing are a consequence of completely overriding the process and the env object.
 
Could you try replacing it with something like this?
```js
if (!(window as any).process) {
    (window as any).process = {env: {} }
} else if (!(window as any).process.env){
    (window as any).process.env = {}
} else {
    (window as any).process.env.DEBUG = undefined
}
```

**Comment by Loghrenar** [comment]
Ok @tkrugg, i replaced the current fix with your one but sadly i'm still facing the issue.

I can confirm that `aws-amplify` and the `aws-sdk` use the process and env object. The problem is 99,9% sure to be that.

**Comment by jtushar53** [comment]
Hi,

Tried multiple workaround but no luck,

after some debugging found that condition to check if env is node or browser is failing.

condition inside validatePayload function in param_validator.js


Solved it by adding below line of code when dom ready event (in my case platform.ready event, i am using Ionic framework)

`        AWS.util.isNode = () => false;
`

Hope it helps someone
