### ISSUE TITLE
Add documentation on master branch

### ISSUE THREAD

**Issue by iam4x** [algolia/angular-instantsearch#34]
It's a bit a pain to have to change branch to update the documentation, I would like the documentation update to be linked with a feature PR.

* [ ] Add documentation into master branch
* [ ] Make a release script that will push the documentation folder on `gitbook` branch

Check as well https://github.com/GitbookIO/gitbook-cli which can build documentation locally for development purpose.

**Comment by vvo** [comment]
> It's a bit a pain to have to change branch to update the documentation

👍
