### ISSUE TITLE
TypeError: _co.state.toggleShowMore is not a function

### ISSUE THREAD

**Issue by corentin-gautier** [algolia/angular-instantsearch#371]
Hi !

When using a searchable limited refinementList:

- search for something
- click the "show more" button
- "toggleShowMore is not a function"

I believe I saw an issue about this but i can't remember where ...

**Comment by Haroenv** [comment]
We should probably have thrown a clearer error there, but for now searchable and show more can't be used at the same time.

**Comment by francoischalifour** [comment]
I believe we've been working on a fix for this in InstantSearch.js: algolia/instantsearch.js#3082.
