### ISSUE TITLE
Rely on connectors `transformItems`

### ISSUE THREAD

**Issue by francoischalifour** [algolia/angular-instantsearch#372]
Since [InstantSearch.js 2.10.0](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#2100-2018-08-08), we support `transformItems` at the connector level. Relying on this abstraction level would allow to share more code and to reduce the maintenance of Angular InstantSearch.

As an example, this manual computation:

https://github.com/algolia/angular-instantsearch/blob/cea7e69ef26aa7befaeaca1bbb4eba944331c22b/src/refinement-list/refinement-list.ts#L106-L108

Could be made passing the `transformItems` option to the `createWidget` call:

https://github.com/algolia/angular-instantsearch/blob/cea7e69ef26aa7befaeaca1bbb4eba944331c22b/src/refinement-list/refinement-list.ts#L112-L118

**Comment by tkrugg** [comment]
fixed by all the PRs referencing this issue.
