### ISSUE TITLE
SearchBox with disabled searchAsYouType doesn't work

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#375]
**Describe the bug 🐛**

A user cannot trigger a search when `searchAsYouType` is disabled. When we press "Enter" or the "Submit" button nothing happens.

**To Reproduce 🔍**

1. Go to https://codesandbox.io/s/0y36l4v1pw
2. Type into the search box
3. Type on "Enter" or click on the "Submit" button
4. Nothing happens

**Expected behavior 💭**

The search box should trigger a search on "Enter" or click on the "Submit" button.

**Comment by dbozman** [comment]
Any update on this bug? We're fighting the same thing.

**Comment by tkrugg** [comment]
Hi @dbozman 
We'll release 2.2.0 next week featuring a fix for this issue.
