### ISSUE TITLE
RefinementList the "Show more" button doesn't have any styles

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#377]
**Describe the bug 🐛**

The "Show more" of the RefinementList don't have any styles.

**Actual**

![screenshot 2018-11-15 at 17 43 01](https://user-images.githubusercontent.com/6513513/48567687-fcc5ee00-e8fd-11e8-82bf-5980aa6bed7b.png)

**Should be**

![screenshot 2018-11-15 at 17 43 18](https://user-images.githubusercontent.com/6513513/48567691-ff284800-e8fd-11e8-830e-7fce6c52dcb5.png)

**Comment by tkrugg** [comment]
I noticed it's not styled on instantsearch.js neither.
Here is an example: https://codesandbox.io/s/2p7lny4qry
Am I using this right?

**Comment by francoischalifour** [comment]
InstantSearch.js 2 doesn't implement the InstantSearch.css spec, so it is somehow expected that the button isn't styled as Angular InstantSearch (and other flavors).

The version 3 styles the button accordingly ([see RefinementList story](https://v3--instantsearchjs.netlify.com/stories/?selectedStory=RefinementList.with%20show%20more)).

**Comment by tkrugg** [comment]
thanks @francoischalifour it's clear now.
