### ISSUE TITLE
Consider to always provide a template with exposed props

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#378]
Right now the current process to customise a component is a bit cumbersome. We can leverage some Angular feature to have the same kind of API that we have with Vue InstantSearch (with slots). Here is a trivial example with a Toggle component (see below). With this API we don't have to manually create a component with the connector, etc... We can directly override the output from the template, it's very similar to the slots in Vue and render props in React. 

**Disclaimer**: not sure that it's the "standard" way to let the user have the full control on the render.

-----

**Implementation:**

```ts
import { Component, ContentChild, TemplateRef } from '@angular/core';

@Component({
  selector: 'app-toggle',
  template: `
    <ng-container
      *ngTemplateOutlet="
        template ? template : defaultToggleTemplate;
        context: { on: state, toggle: toggle }
      "
    ></ng-container>

    <ng-template #defaultToggleTemplate let-state="on" let-toggle="toggle">
      <div>inner = '{{ state }}'</div>
      <button (click)="toggle()">Toggle</button>
    </ng-template>
  `,
})
export class ToggleComponent {
  @ContentChild(TemplateRef) public template?: TemplateRef<any>;

  state = false;

  toggle = () => {
    this.state = !this.state;
  };
}
```

**Usage:**

```html
<app-toggle></app-toggle>

<app-toggle>
  <ng-template let-state="on" let-toggle="toggle">
    <p>This is a custom render of the component.</p>
    <label>
      <input type="checkbox" (change)="toggle()" hidden />
      <span>{{ state ? '✅' : '❌' }}</span>
      <span>The input is {{ state ? 'checked' : 'unchecked' }}</span>
    </label>
  </ng-template>
</app-toggle>
```

Here is the live example on [CodeSandbox](https://codesandbox.io/s/oo0w604y6z).

**Comment by tkrugg** [comment]
It totally makes sense.
It totally makes sense. So would this replace entirely the need for BaseWidget?

**Comment by samouss** [comment]
Internally or externally? Because we still have to extends from it internally.

**Comment by tkrugg** [comment]
I meant externally. I was thinking not advertising its usage at all.
Reading the documentation I think maybe it's still the answer to some complex use cases (eg. overriding a refine method)

nevermind. Sounds good. I'll list here the components that need it then start this.

**Comment by samouss** [comment]
Yep indeed for use case where we don't have a widget implemented but the connector exist (e.g. [connectAutocomplete](https://community.algolia.com/instantsearch.js/v2/connectors/connectAutocomplete.html)). But even with this we can reduce the boilerplate code to extend this class. There is some abstraction that leaks a bit: like the BEM root element or even the fact that the user have to manually call the connector.

**Comment by tkrugg** [comment]
## Components for which we want to add support for ng-template
- [ ] breadcrumb
- [ ] clear-refinements
- [ ] configure
- [ ] current-refinements
- [ ] hierarchical-menu
- [ ] highlight
- [x] hits
- [ ] hits-per-page
- [ ] infinite-hits
- [ ] instantsearch
- [ ] menu
- [ ] numeric-menu
- [ ] numeric-selector
- [ ] pagination
- [ ] panel
- [ ] range-input
- [ ] range-slider
- [ ] rating-menu
- [ ] refinement-list
- [ ] search-box
- [ ] sort-by
- [ ] stats
- [ ] toggle
