### ISSUE TITLE
No way to define routing.router function

### ISSUE THREAD

**Issue by Omi0** [algolia/angular-instantsearch#390]
https://github.com/algolia/angular-instantsearch/blob/de2a85ac695f5569cd83f8500c3b304572e2f40b/src/instantsearch/instantsearch.ts#L178

Our aim to to use SEO friendly URLs with a custom titles for different filters as mentioned here (https://community.algolia.com/instantsearch.js/v2/guides/routing.html#seo-friendly-urls)
But, unfortunately there is no way to define router settings as well as to use instantsearch.routers.history, because for routing we can only define stateMapping.

Is there is a way to define router settings for routing?

**Comment by Haroenv** [comment]
It’s the type which is written wrong, could you add a pr to add the routing part (object with read, write, createURL, dispose, all functions). Or can you @tkrugg?

**Comment by Haroenv** [comment]
In the mean time, you should be able to pass “as any” to the router param

**Comment by Omi0** [comment]
As workaround I tried change the type to <any> and write functions, then there were complains about instantsearch.routers.history

Dont remember which one though. Gonna check tomorrow. 

Also gonna extend a type and pr it.

**Comment by Haroenv** [comment]
Thanks!

**Comment by Omi0** [comment]
Hmm.. Still can't get to the history function, imports like
`import instantsearch from 'instantsearch.js/es';`
 simply causing
`history is not a function` errror...

-----------------
@ViewChild('instantsearchRef')
  private instantsearchRef: NgAisInstantSearch;

this.instantsearchRef.instantSearchInstance
doesn't work either to get BrowserHistory function...

------------------
What am I missing @Haroenv ?
