### ISSUE TITLE
want to load instasearch results by default

### ISSUE THREAD

**Issue by supportast** [algolia/angular-instantsearch#392]
this.query = 'test';
searchChanged(query) {
    console.log(query);
    if (query.length  > 2) {
      this.showResults = true;
    } else {
      this.showResults = false;
    }
  }

Above is not working for me, It is showing all results rather than passed query text.
can anyone suggest how to do that?

**Comment by Haroenv** [comment]
It would be very useful to create what you have so far in a sandbox environment. We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/angular-instantsearch). Thanks!

**Comment by tkrugg** [comment]
@supportast closing this as there has been no response. Feel free to reopen it if you issue is not fixed.
