### ISSUE TITLE
Customized Toggle Widget Errors

### ISSUE THREAD

**Issue by benjing** [algolia/angular-instantsearch#394]
I am trying to customize the toggle button, using the custom widget documentation (https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html). But I have not been able to get the data from the state, data like the name and count of value. 
custom widget component:
![capture](https://user-images.githubusercontent.com/41148056/49573455-fb299c00-f978-11e8-8d2f-fd3d3170984f.PNG)
error message:
![capture1](https://user-images.githubusercontent.com/41148056/49573483-08df2180-f979-11e8-82a8-1dbb42028b26.PNG)

**Comment by benjing** [comment]
Here is a sandbox customized to with the template, as you can see in the toggle component i try to call state.value in the count of the toggle, it gives me back an object but when i put state.value.count it gives errors
SandBox:
https://codesandbox.io/s/jv7yn80j0v

**Comment by Haroenv** [comment]
I was able to make it work, but note that `refine` takes `state.value` as its parameter. 

Note that while `state` will be an object; `state.value` isn't always defined, so you need to put it in a guard (`state.value && state.value.count`). 

Here's a version which is fixed.

https://codesandbox.io/s/3xyr76oqlp

However, that version still hardcodes the facet to toggle in question, to be correct, you'd need to read the values you pass on `ngOnInit` to the `createWidget` call should be coming from `@Input`s, from your template. 

I hope that helps you, feel free to continue commenting if this didn't solve the issue for you, and we will reopen the issue. 

Have a nice day!
