### ISSUE TITLE
Remove ClearAll button from CurrentRefinements widget

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#405]
**Describe the bug 🐛**

The button of the CurrentRefinement don't have the correct style for the disabled state (see [DevNovel](https://community.algolia.com/angular-instantsearch/examples/dev-novel/?selectedStory=CurrentRefinements.default)).

**Actual**

![screenshot 2018-12-20 at 12 28 36](https://user-images.githubusercontent.com/6513513/50282367-d510fb00-0452-11e9-847a-83241cc4510a.png)

**Should be**

![screenshot 2018-12-20 at 12 28 52](https://user-images.githubusercontent.com/6513513/50282383-e4904400-0452-11e9-8bef-d7588620b025.png)

**Comment by tkrugg** [comment]
I can't find any equivalent to this "Clear all filters" button in [VanillaJS](https://www.algolia.com/doc/api-reference/widgets/current-refinements/js/). I'm surprised to see it here.

It seems it was always there: https://github.com/algolia/angular-instantsearch/commit/32ad581739c4757e331b2013498801f84bdee6bc

**Comment by samouss** [comment]
Yep my bad the "Clear all" button doesn't exist anymore on [`CurrentRefinements`](https://instantsearch-css.netlify.com/widgets/current-refinements/). We should drop his support in the next major to match the rest of the flavours.

**Comment by francoischalifour** [comment]
The button is now part of the widget [`clearRefinements`](https://www.algolia.com/doc/api-reference/widgets/clear-refinements/js/) in InstantSearch.js.
