### ISSUE TITLE
InfiniteHits the "Show more" button doesn't have the correct style

### ISSUE THREAD

**Issue by samouss** [algolia/angular-instantsearch#406]
**Describe the bug 🐛**

The "Show more" of the InfiniteHits doesn't have the correct styles.

**Actual**

![screenshot 2018-12-20 at 12 27 20](https://user-images.githubusercontent.com/6513513/50282432-07225d00-0453-11e9-92ad-7c7c7f74ceaf.png)

**Should be**

![screenshot 2018-12-20 at 12 28 06](https://user-images.githubusercontent.com/6513513/50282435-08ec2080-0453-11e9-9615-77295ab08dd9.png)

**Comment by tkrugg** [comment]
currently the CSS class applied is `ais-InfiniteHits-showMore` but we should be applying `ais-InfiniteHits-loadMore`.
Let change it.
Qualifying this as a breaking change.
