### ISSUE TITLE
Make instantsearch.js a peer dependency

### ISSUE THREAD

**Issue by tkrugg** [algolia/angular-instantsearch#433]
Related: 
- PR: https://github.com/algolia/angular-instantsearch/pull/333
- https://github.com/algolia/doc-code-samples/issues/41

**Comment by tkrugg** [comment]
solved in #463

**Comment by francoischalifour** [comment]
It's still [a dependency](https://github.com/tkrugg/angular-instantsearch/blob/9e172631b50143d4faf5f1a8ffa9efbbcf93498f/examples/storybook/package.json#L18), not a peer dependency.

**Comment by tkrugg** [comment]
You’re looking at the package file of an example 
This is the one you want
(Note that it’s only on the v3 branch)

https://github.com/algolia/angular-instantsearch/blob/v3/package.json
