### ISSUE TITLE
Angular Universal (SSR)

### ISSUE THREAD

**Issue by iam4x** [algolia/angular-instantsearch#44]
This issue will be split into two PRs:

* [x] Ensure `angular-instantsearch` can be run on the server side (no errors of rendering)
* [x] Request Algolia API on the server to populate the page with data

The first part would pretty easy to achieve by using:

```ts
 import { PLATFORM_ID } from '@angular/core';
 import { isPlatformBrowser, isPlatformServer } from '@angular/common';
 
 constructor(@Inject(PLATFORM_ID) private platformId: Object) { ... }
 
 ngOnInit() {
   if (isPlatformBrowser(this.platformId)) {
      // Client only code.
      ...
   }
   if (isPlatformServer(this.platformId)) {
     // Server only code.
     ...
   }
 }
```

The second part is more difficult, we would have to:

1. Gather all the widgets mounted on the page and their configuration
2. Compute the helper state from the URL query
3. Fetch data from Algolia API
    * We have noticed that using the `HttpClient` from Angular blocks the rendering into `ngOnInit()` life cycle hooks of a component. It implies writing an [algolia search client](https://github.com/algolia/algoliasearch-client-javascript) adapter working with the `HttpClient` and use it with Angular InstantSearch.
4. Populate data into the different widgets state

Right now we did not found a way to have the same logic of the React-InstantSearch for the SSR which is:

1. First render on server -> Gather all the widgets and their configurations
2. Query Algolia API
3. Populate data into the widgets
4. Second render on server with the data

If you have any idea on how to achieve the above solution with https://www.npmjs.com/package/@nguniversal/express-engine please tell us 🙏

**Comment by iam4x** [comment]
The first two parts are now done, but we need more:

* [ ] Implement universal transfer state on widgets in order to keep server & browser state synced
* [ ] Apply SearchParameters from URL on server search query

I found this nice article about transfer state: https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c

I have opened the PR if you want to take a look on the code 👍

**Comment by iam4x** [comment]
Quick update, the SSR now works correctly but it will be only supported starting with Angular version 5.

* First search request is only done on the server side
* We need to use [preboot](https://github.com/angular/preboot) in order to avoid a blink of the UI when Angular does the first render on browser side
* We need to write a bit of boilerplate code in order to make SSR works

Next steps:

* [ ] Write the documentation / guide
* [ ] Release a new beta 👍

**Comment by iam4x** [comment]
It has been released with 1.0.0-beta.6 🎉

**Comment by RudiPersson** [comment]
Is Algolia SSR going to be supported on Angular version 6 ?

**Comment by Haroenv** [comment]
This should already be supported @RudiPersson, please open a new issue with a failing reproduction if you have any issues :)

**Comment by RudiPersson** [comment]
According to the offical documentation / guide instructions at [https://community.algolia.com/angular-instantsearch/guides/server-side-rendering.html](url) 
> Angular Universal is not working completely with version 6, you will need to checkout a specific commit of universal-start boilerplate.

@Haroenv  should this be ignored ?
