### ISSUE TITLE
Cannot change index programmatically

### ISSUE THREAD

**Issue by cyworks** [algolia/angular-instantsearch#457]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: I would like to change indexName programmatically like the ais-sort-by component. Thank you

**Comment by Haroenv** [comment]
You can make a custom component using connectSortBy

**Comment by tkrugg** [comment]
Hi @cyworks. 
To create your custom component on top of `connectSortBy` please refer to our [guide]( https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html)
In your case, looking at the code of our [ais-sort-by](https://github.com/algolia/angular-instantsearch/blob/develop/src/sort-by/sort-by.ts) component can also be a good starting point.
