### ISSUE TITLE
Providing a rendering HTML code block (instead of just facet value)

### ISSUE THREAD

**Issue by sajidniazi** [algolia/angular-instantsearch#458]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: Current refinements has a transformItems attribute which allows for transforming a value e.g., project id=123123 to a project name for display purpose. However, there is no way to provide the actual render code to display the value along with proper html.
E.g., if the facet values color codes (#fff, #000 etc), I would like to actually show the visual color to the user instead of the color code.

https://community.algolia.com/angular-instantsearch/widgets/current-refinements.html

**Comment by tkrugg** [comment]
HI @sajidniazi. Thanks for reaching out. 

If you want to customize the underlying HTML, it's best you create your own CurrentRefinement component, by combining the `BaseWidget` class and the `connectCurrentRefinedValues`, like described in the [_Customize widgets_ guide](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html).

There are two things I should add:
- we'll soon (end of February) release a revamp for our Angular InstantSearch docs that will contains a lot more code samples explaining how to customize the rendering of every widget we provide
- we have an ongoing work for allowing rendering customisation via `ng-template`, tracked by this issue: https://github.com/algolia/angular-instantsearch/issues/378

Following the [_Customize widgets_ guide](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html) should get you going, let me know if your have trouble with it. 

I'm closing this for now. Feel free to reopen it.

**Comment by sajidniazi** [comment]
```
import { Component, OnInit, Inject, forwardRef } from '@angular/core';
import { BaseWidget, NgAisInstantSearch } from 'angular-instantsearch';
import { connectRefinementList } from 'instantsearch.js/es/connectors';

@Component({
  selector: 'app-colorfacet',
  // templateUrl: './colorfacet.component.html',
  template: `
  <ul [ngStyle]="{'margin': '0', 'padding': '0', 'list-style': 'none'}">
    <li
      *ngFor="let item of state.items"
      (click)="refine2($event, item)">
      <label [class]="cx('label')">
        <input
          [class]="cx('checkbox')"
          type="checkbox"
          value="{{item.value}}"
          [checked]="item.isRefined"
        />
        <span [ngStyle]="{'background-color': item.value}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <span [ngStyle]="{
          'padding': '.1rem .4rem',
          'font-size': '.8rem',
          'color': '#3a4570',
          'background-color': '#dfe2ee',
          'border-radius': '8px'
        }"> ({{item.count}})</span>
      </label>
    </li>
  </ul>
  `
})
export class ColorfacetComponent extends BaseWidget implements OnInit {
  state: {
    canRefine: false,
    canToggleShowMore: false,
    createURL: (...args: any[]) => {},
    isShowingMore: false,
    items: { label: string; value: string }[],
    refine:  (...args: any[]) => {},
    toggleShowMore: (...args: any[]) => {},
    searchForItems: (...args: any[]) => {},
    isFormSearch: false,
  };

  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchParent
  ) {
    super('ColorfacetComponent');
  }

  public ngOnInit() {
    this.createWidget(connectRefinementList, { attributeName: 'color' });
    super.ngOnInit();
  }
// https://github.com/algolia/angular-instantsearch/blob/develop/src/refinement-list/refinement-list.ts
  public refine2(
    event: MouseEvent,
    item: { isRefined: boolean; value: string }
  ) {
    event.preventDefault();
    event.stopPropagation();

    if (this.state.canRefine) {
      // update UI directly, it will update the checkbox state
      item.isRefined = !item.isRefined;

      // refine through Algolia API
      this.state.refine(item.value);
    }
  }

}


```
