### ISSUE TITLE
Date range in Facet values

### ISSUE THREAD

**Issue by sajidniazi** [algolia/angular-instantsearch#459]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: Date range/menu in Facet value. Currently, we numeric value so users can e.g., narrow down pricing within a certain range using the numeric menu. Is it possible to add something similar for date ranges, so the users can easily narrow down the data based on a date range? Date created: Today, This week, This month, This Quarter, This year.

https://community.algolia.com/angular-instantsearch/widgets/numeric-menu.html

**Comment by tkrugg** [comment]
Hi again @sajidniazi 😄 
Thank for bringing up all the issues you're facing. It helps us improve our docs.

First thing to note is that to enable filtering on dates you'll need them to be expressed as timestamps, as explained in our guide [Filter by Date](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-date/).

Once your dates are integers, you can combine the `BaseWidget` class and the  `connectRange`  connector to create a widget that allows filtering on date ranges. This approach will give you full control on the markup and the look.

You can refer to our own [RangeInput](https://github.com/algolia/angular-instantsearch/blob/develop/src/range-input/range-input.ts) as well as our [_Customize Widgets_ guide](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html) for help. 

Let me know if you're facing issues with this. 
Closing this for now, feel free to reopen it.

**Comment by smomin** [comment]
Algolia recommends saving dates as unix timestamp.  https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/what-is-in-a-record/#dates
