### ISSUE TITLE
Why can I not mount two search boxes on the same page?

### ISSUE THREAD

**Issue by astr0sl0th** [algolia/angular-instantsearch#461]
I cannot seem to mount two custom search boxes on the same page

**To Reproduce 🔍**

Mount two search boxes on the same page

**Expected behavior 💭**

**Screenshots 🖥**

N/A

**Environment:**

 - Angular 7.1.3
- "instantsearch.js": "^2.8.0",
- "angular-instantsearch": "^2.1.0",

**Additional context**

I get an error saying `Cannot read property 'addWidget' of undefined`

**Comment by Haroenv** [comment]
It would be very useful to create what you have so far in a sandbox environment. We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch). Thanks!

This should work regularly. Are you maybe trying to mount the search box outside of an ais-instant-search root?

**Comment by astr0sl0th** [comment]
I don't know if it is me more stackblitz but I cannot seem to even get a basic demo of one search working. Do you have a basic example I can adapt?

**Comment by Haroenv** [comment]
There's a basic example here: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch

**Comment by astr0sl0th** [comment]
Sorry my bad I was trying to mount he my custom widget outside the ais-instant-search root.
