### ISSUE TITLE
Could not find module in path: 'angular-instantsearch'

### ISSUE THREAD

**Issue by Newbie012** [algolia/angular-instantsearch#464]
**Describe the bug 🐛**

```
Could not find module in path: 'angular-instantsearch'
```

On version `2.2.0`

**To Reproduce 🔍**

1. Upgrade to version `^2.2.0`

A live example helps a lot! We have a simple online template for you to use for your explanations:

> https://codesandbox.io/s/m5qzwnq158

**Expected behavior 💭**

Should find the module.

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/10504365/52593858-add31a80-2e52-11e9-8c2d-856f3beafd91.png)

**Environment:**

 - OS: [iOS / windows / mac / android]
 - Browser [compiler]
 - Version ^2.2.0

**Comment by tkrugg** [comment]
Hi @Newbie012. Thanks a lot for reporting that. 
2.2.0 publishing was not successful. I just unpublished it.
We published 2.2.1, which works https://codesandbox.io/s/y03kpr79wj
