### ISSUE TITLE
Unable to autofocus searchbox

### ISSUE THREAD

**Issue by lukemoderwell** [algolia/angular-instantsearch#465]
**Describe the bug 🐛**

AIS searchbox is not autofocused even when autofocus input is set to true. See code below:

`<ais-search-box [autofocus]='true' placeholder="Search"></ais-search-box>`

I've read through PR #208 and this seems to add the autofocus feature. Maybe I'm not implementing it correctly?

**To Reproduce 🔍**

A live example helps a lot! We have a simple online template for you to use for your explanations:

> https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**

 - OS: mac (10.14.2)
 - Browser: Chrome
 - Version 71.0.3578.98

**Additional context**

**Comment by samouss** [comment]
Which version of Angular InstantSearch are you using? I tried with the [CodeSandbox example](https://codesandbox.io/s/6y0z5qmzvk) and it does work on my side. Note that this option is available only on the version `2.1.0` and higher.

**Comment by lukemoderwell** [comment]
@samouss my package.json has: `"angular-instantsearch": "2.1.0"`

Thanks for including the example. I'll check through and see if I can see any glaring differences.

**Comment by lukemoderwell** [comment]
I've tracked this back to the usage of Google Tag Manager. When I remove our tag manager script from `index.html` suddenly autofocus works 🤷‍♀️. Not sure what script exactly but will continue to debug.

**Comment by tkrugg** [comment]
Thanks @lukemoderwell for keeping us posted.
Closing this for now. If you conclude that there is still something we need to fix on our side, feel free to reopen.

**Comment by lukemoderwell** [comment]
@tkrugg nothing on Algolia's side. The issue was tracked down to this bit of code in our index.html: 
```
  try {
      Typekit.load({
        async: true
      });
    } catch (e) {
      console.error(e);
    }
```

Seems like somehow our fonts loading removes focus on the search input. I've resolved by moving this down the page. Thanks again to @samouss for taking the time to help.

**Comment by samouss** [comment]
Thanks for letting us know! Glad to see that you solved your issue.
