### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by AndrewNyaisonga** [algolia/angular-instantsearch#477]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: the live example of MenuSelect on BaseWidget. The widget showcase link returns 404 not found.

**Comment by tkrugg** [comment]
Hi @AndrewNyaisonga 
The MenuSelect example is here, alive and kicking: https://community.algolia.com/angular-instantsearch/examples/storybook/?selectedKind=Custom%20widgets&selectedStory=MenuSelect&full=0&addons=1&stories=1&panelRight=0.
For v2, the code is of this example is located [here](https://github.com/algolia/angular-instantsearch/blob/develop/examples/storybook/src/custom-widgets.ts#L10-L39). If you're using v3 (which is in beta), that code sample you want to look at is on the  [v3 branch](https://github.com/algolia/angular-instantsearch/blob/v3/examples/storybook/src/custom-widgets.ts#L10-L68).

Could you point us exactly to where you found the broken link? I would like to fix it but I couldn't find it.

**Comment by AndrewNyaisonga** [comment]
Hi @tkrugg 
Thank you. The broken link is on this [documentation on BaseWidget](https://community.algolia.com/angular-instantsearch/guides/customize-widgets.html) All the way to the bottom when it links you to the live example.

**Comment by tkrugg** [comment]
Thank you @AndrewNyaisonga. I just made a PR to fix it.
