### ISSUE TITLE
Search results in dropdown

### ISSUE THREAD

**Issue by matiishyn** [algolia/angular-instantsearch#53]
Hi all
Is it possible to make a dropdown out of `angular-instantsearch` or maybe combine it with Bootstrap Typeahead (https://ng-bootstrap.github.io/#/components/typeahead/examples)?

**Comment by Haroenv** [comment]
Not angular InstantSearch without some research, but you can already use our autocomplete.js with Angular IIRC: https://github.com/algolia/autocomplete.js/blob/master/README.md#angularjs

**Comment by matiishyn** [comment]
but autocomplete.js is for AngularJS 1.x,
I'm looking for similar variant for Angular (2,4,5)

**Comment by ng-darren** [comment]
Hi matiishyn,

I implemented my own autocomplete dropdown using angular-instantsearch. It is basically an <ul> with a little bit of CSS to make it look like a dropdown below the input. Here's what I did my html.

```
<ng-ais-instantsearch [config]="config.algolioConfig">
    <div class="row">
        <div class="col">
            <ng-ais-search-box (change)="searchChanged($event)" resetTitle="reset" submitTitle="search"></ng-ais-search-box>
              <ng-ais-results *ngIf="searchValue">
                <ng-template let-hits="hits">
                  <ul class="customSelect" *ngIf="hits && hits.length">
                    <li *ngFor="let hit of hits" (click)="hitSelected(hit)">
                      <img [src]="hit.thumbnail" alt="">
                      <small *ngIf="hit.name">
                        <ng-ais-highlight attributeName="name" [hit]="hit"></ng-ais-highlight>
                      </small>
                    </li>
                  </ul>
                </ng-template>
              </ng-ais-results>
             .
             .
             .
```

**Comment by iam4x** [comment]
@ng-darren @matiishyn 

The new release of the library (beta8) includes a way to write your custom widgets easily, the guide is available [in the documentation here](https://algolia.gitbooks.io/angular-instantsearch/content/custom-widgets.html).

I'll be happy to have your feedback 👍
