### ISSUE TITLE
Current Refinements Attributes Does nothing

### ISSUE THREAD

**Issue by logan-jobzmall** [algolia/angular-instantsearch#563]
When providing a name/label mapping through the [attributes] binding, it does absolutely nothing

**Expected behavior 💭**

For it to map the labels appropriately with the attribute names

**Comment by yannickcr** [comment]
Seems the documentation for the `ais-current-refinements` widget is not up to date :disappointed: .

Unlike what is documented, the `ais-current-refinements` does not have an [attributes] binding so it is not possible to provite a name/label mapping this way.

To do what you want you will need to create your own UI using the `connectCurrentRefinement` connector: https://www.algolia.com/doc/api-reference/widgets/current-refinements/angular/#connector

**Comment by tkrugg** [comment]
Yannick is right, documentation is out of date. Thanks for spotting that @logan-jobzmall. It's currently being fixed and about to be deployed. This is the usage of the component.

```html
<ais-current-refinements
  // Optional parameters
  [includedAttributes]="string[]"  // by default, includes all attributes
  [excludedAttributes]="string[]"  // by default is `['query']`
  [transformItems]="function"      // by default is the identity `items => items`
></ais-current-refinements>

```

You can use it in the following way: 

```html
<ais-current-refinements
  [includedAttributes]="['categories']"
  [excludeAttributes]="['brand']"
  [transformItems]="transformItems"  
></ais-current-refinements>
 
transformItems(items) {
  return items.map(item => ({
    ...item,
    label: item.label.toUpperCase(),
  }));
},

```

Let us know if this helps
