### ISSUE TITLE
Angular InstantSearch widget configuration object has been updated.

### ISSUE THREAD

**Issue by shrestaz** [algolia/angular-instantsearch#564]
On the documentation of Angular InstantSearch implementation example [here](https://community.algolia.com/angular-instantsearch/widgets/instantsearch.html#code-example), the config object provided has been changed in the Algolia API reference docs.

The updated implementation should be: [(link to official documentation)](https://www.algolia.com/doc/api-reference/widgets/instantsearch/angular/?language=angular#examples)
```typescript
import * as algoliasearch from 'algoliasearch/lite';

@Component({
  template: `
    <ais-instantsearch [config]="config">
      <!-- Widgets -->
    </ais-instantsearch>
  `,
})
export class AppComponent {
  config = {
    indexName: 'instant_search',
    searchClient: algoliasearch('YourApplicationID', 'YourSearchOnlyAPIKey'),
  }
}
```
**To Reproduce 🔍**

Follow the current documentation of config setup.
Instantsearch fails to initialize.

**Expected behavior 💭**

InstantSearch should initialize as expected.

**Errors 🖥**
`ERROR TypeError: Cannot read property 'addAlgoliaAgent' of undefined`
`ERROR TypeError: Cannot read property 'addWidget' of undefined`

**Environment:**

 - OS: Arch Linux
 - Chrome Version 74.0.3729.157 (Official Build) (64-bit)
 - Angular-InstantSearch": 3.0.0-beta.0
 - InstantSearch.js: 3.1.1
 - AlgoliaSearch: 3.32.0

**Additional context**

Follow the official API documentation for fix.
https://www.algolia.com/doc/api-reference/widgets/instantsearch/angular/?language=angular#examples

**Comment by Haroenv** [comment]
note that the doc on Algolia.com is for v3 beta, and the community website v2

**Comment by shrestaz** [comment]
@Haroenv Somehow I missed that part and spent some time debugging. Please close the issue since it's not relevant.
