### ISSUE TITLE
Request: Disable automatic search when a widget is added/removed

### ISSUE THREAD

**Issue by Kamshak** [algolia/angular-instantsearch#596]
**Is your feature request related to a problem? Please describe 🙏**

Right now when you remove a widget it will start a new search. This is an issue in two cases:
1) Component is destroyed: Widgets are removed 1 by 1 and a trove of search requests is created. This causes perf issues and costs money :)
2) We intentionally hide a filter. We do this because we allow to search different types of products that are in the same index. Since most of the UI stays the same, we simply *ngIf the filter component. Unfortunately, when removing it and the instantsearch was started already, a search request is done for each widget that is added/removed. This causes a lot of unnecessary searches.

**Describe the solution you'd like 🤔**

Would like to have a way to disable automatically triggering a search when adding and removing widgets.

**Describe alternatives you've considered ✨**

1) Forking the library and simply disabling the functionality. Not such a great solution since we'd need to maintain it and I expect the lib will change a bit, considering this is a beta.
2) Try to use the searchFunction to disable search temporarily until the transition is completed. This doesn't seem to work very well unfortunately, not sure why. Very tricky to figure out and manage the state correctly here.

**Comment by Haroenv** [comment]
When removing multiple widgets after eachother, only a single request will be fired, but each addition will indeed cause a new request in some use cases when it spans over multiple micro tasks. Do you have a sandbox of how you're using Angular InstantSearch now, so we can see how it can be optimised?

We have a sandbox available http://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch

**Comment by tkrugg** [comment]
closing this for now. Feel free to reopen @Kamshak if you want to further continue the discussion.
