### ISSUE TITLE
Update package to be Angular 8 compliant

### ISSUE THREAD

**Issue by dauledk** [algolia/angular-instantsearch#599]
Installing this package with Angular v8 gives the following warn:

```
npm WARN angular-instantsearch@3.0.0-beta.1 requires a peer of @angular/common@>=5.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-instantsearch@3.0.0-beta.1 requires a peer of @angular/core@>=5.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-instantsearch@3.0.0-beta.1 requires a peer of @angular/platform-browser@>=5.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-instantsearch@3.0.0-beta.1 requires a peer of @angular/platform-browser-dynamic@>=5.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by samouss** [comment]
Thanks for opening this! It's something that we'll tackled in the coming weeks. We want to ensure that everything is working fine with Angular 8 before bumping the peer dependencies.

**Comment by dauledk** [comment]
Sounds like a plan @samouss. But why not release the angular v8 compliant under a beta flag, so we can help test? This would also help paint a picture of Algolia as a fast moving company. If `angular-instantsearch` is gonna be 1-4 weeks behind angular's releases, we are gonna se the warnings in the terminal 2 out of 12 months in a year 😢 I don't know if it's only me, but I don't like warnings on _every_ npm install/audit 😀

**Comment by francoischalifour** [comment]
Hi @dauledk – the reason why we're not so responsive on this kind of updates is because we lack human resources in the team. We've got a roadmap and didn't prioritize Angular 8 support enough in the list.

This is a balance that we're still trying to find and we're not there yet. We definitely want to improve on that side and be more proactive in the frameworks we support. As @samouss mentioned, we should tackle this in the coming weeks.

Keep in mind that Angular InstantSearch is an open source project – we'd also love some contributions from the community :)

**Comment by dauledk** [comment]
@francoischalifour thanks for the detailed answer. I had the impression that Algolia supported the project, but if it's a stand alone open source - then it's a completely different situation, and I completely understand the roadmap/limited resources  :)

**Comment by dauledk** [comment]
Is this change released? Because I am still getting warnings with version `^3.0.0-beta.2`.

**Comment by tkrugg** [comment]
We're about to :) I'll let you know here!

**Comment by tkrugg** [comment]
Hi @dauledk We've just release .beta-4 that officially accepts angular 8 as a peer dependency. We just needed time to confirm everything worked. Thanks!
