### ISSUE TITLE
attribute === 'highlighted' at ais-highlight

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/angular-instantsearch#625]
**Describe the issue**

In Angular-InstantSearch, `ais-highlight` component has [a special treatment](https://github.com/algolia/angular-instantsearch/blob/f79951a9afdcde83b70eff87c63488a091a081cb/src/highlight/highlight.ts#L17) when `attribute === 'highlighted'`.

I couldn't find same thing in other flavors. And this is not addressed in [the spec](https://instantsearch-css.netlify.com) or in [the doc](https://www.algolia.com/doc/api-reference/widgets/highlight/angular/).

Can I get some background on this? If this is not needed anymore, we can remove the part and perhaps replace some of the code with `highlight` function from `instantsearch.js/es/helper`.

cc @tkrugg

**Comment by yannickcr** [comment]
It is not documented but it is still used internally by `src/refinement-list/refinement-list.ts` https://github.com/algolia/angular-instantsearch/blob/869def1/src/refinement-list/refinement-list.ts#L61

It was added by https://github.com/algolia/angular-instantsearch/pull/18, I don't know if it is a behavior we want to keep.

**Comment by samouss** [comment]
Yes it's expected. We use it to highlight the results of `searchForFacetValues` (e.g [`ais-refinement-list`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/angular/#widget-param-searchable)). The results come back with an [`highlighted`](https://www.algolia.com/doc/api-reference/api-methods/search-for-facet-values/?language=js#method-response-facethit) attribute. We don't document this feature because it's mostly internal. We have a similar approach inside [Vue InstantSearch](https://github.com/algolia/vue-instantsearch/blob/c023ba0fafbb32d556db2895aafec6c3742a1380/src/components/RefinementList.vue#L181-L191). It should be something that we do by default at the connector level to have a transparent usage of the `highlight` function.

**Comment by eunjae-lee** [comment]
Okay, from what I've discovered so far is,
in Vue-IS, `items` at `ais-refinement-list` looks like this:

```js
[
  {
    "highlighted": "<mark>I</mark>nsignia™",
    "count": 746,
    "isRefined": false,
    "value": "Insignia™",
    "label": "Insignia™",
    "_highlightResult": {
      "item": {
        "value": "<mark>I</mark>nsignia™"
      }
    }
  },
  ...
```

but in Angular-IS, `state.items` at `ais-refinement-list` looks like this:

```js
[
  {
    "highlighted": "<mark>I</mark>nsignia™",
    "count": 746,
    "isRefined": false,
    "value": "Insignia™",
    "label": "Insignia™"
  },
  ...
```

`_highlightResult` is missing in Angular-IS for some reason I don't know. And that's why Angular-IS has implemented the special case where `attribute === 'highlighted'`.

**Comment by eunjae-lee** [comment]
The api response of [SFFV] doesn't seem to provide `_highlightResult` property. Does this mean it's somehow injected in Vue-IS while it's not in Angular-IS?
but I couldn't find such code in Vue-IS.

**Comment by samouss** [comment]
Yes, it is. My previous message was linked to the part of the code from [Vue InstantSearch](https://github.com/algolia/vue-instantsearch/blob/c023ba0fafbb32d556db2895aafec6c3742a1380/src/components/RefinementList.vue#L181-L191) that creates the `_highlightResult` structure. The structure of Angular InstantSearch is one returned by the API untouched. We should implement the logic that Vue does directly inside InstantSearch. We could then leverage the `highlight` function of InstantSearch. Note that we should use a different attribute name to avoid any collision with users data.

**Comment by eunjae-lee** [comment]
> Note that we should use a different attribute name to avoid any collision with users data.

Should we? In ais-refinement-list, there's no `_highlightResult` property in the first place. So it should be okay for us to use whatever as the attribute name, which is `item` in case of Vue-IS.

```js
    "_highlightResult": {
      "item": {
        "value": "<mark>I</mark>nsignia™"
      }
    }
```

I was thinking of doing the same as Vue-IS, meaning I'm going to use `item` as an attribute name for this.
Please correct me if I misunderstood anything.

**Comment by samouss** [comment]
Yes you're right. IMO we should not do that inside Angular InstantSearch, it should be done inside InstantSearch directly. Otherwise we re-implement the same logic N times for each flavours.

**Comment by eunjae-lee** [comment]
Okay, let's do it in InstantSearch at first, then move on to the flavors. Closing this issue and the related PR for nwo.
