### ISSUE TITLE
Multiple custom widget range-slider does not filter properly (3.0.0-beta.2)

### ISSUE THREAD

**Issue by tgangso** [algolia/angular-instantsearch#657]
**Describe the bug 🐛**

Using multiple custom range-sliders does not filter the result properly. Using only one works fine.

**To Reproduce 🔍**

Create multiple range-slider filters following this guide: https://www.algolia.com/doc/api-reference/widgets/range-slider/angular/#full-example

Using only one of them gives the expected filtering, having more than one of them active at the same time makes one of them not filter properly.

**Expected behavior 💭**

Correct filtering for all sliders.

**Environment:**

Tested on Chrome on macOS Mojave
"angular-instantsearch": "3.0.0-beta.2"

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch). Thanks!

**Comment by alextrastero** [comment]
I'm also having issues when adding two sliders with different attributes. I cannot reproduce in your sandbox because only `price` can be added to the slider. I've seen then `popularity` attribute but it's `canRefine: false`.

Current sandbox: https://codesandbox.io/s/ais-ecommerce-demo-app-o1li6

**Comment by tkrugg** [comment]
Hi @alextrastero thanks for moving the issue, it helps us keep things tidy 😄.
@tgangso I think you're just missing a binding on the `[value]` attribute.
Add this to you template `[value]="state.start[1]"` and you should get the result you want. 

```html
<div *ngIf="state.range">
  <input
    type="range"
    #input
    [min]="state.range.min"
    [max]="state.range.max"
    (change)="state.refine([state.range.min, input.value])"
    [value]="state.start[1]"
    
  />
  {{input.value}}
</div>
```

Can I ask why you want two range filters on the same attribute?
I've made a code sample: https://codesandbox.io/s/4b0cl
