### ISSUE TITLE
Ability to display facets as InstantSearch results

### ISSUE THREAD

**Issue by softmonkeyjapan** [algolia/angular-instantsearch#660]
Hey everyone,

We recently started implementing Algolia in our Angular App. Everything seems just magic and we're very happy about it.

**Is your feature request related to a problem? Please describe 🙏**
We want to display the facets in realtime instead of `hits` (results). Our goal is to display to the user something like this:
<img width="593" alt="Capture d’écran 2019-07-25 à 15 58 21" src="https://user-images.githubusercontent.com/2499912/61852696-0ffd7480-aef5-11e9-8fb9-9410ff088d43.png">

We already have our facet (`category.name`) return by the API but somehow by reading the doc we couldn't find a way to do it without writing our own custom widget (which we haven't done yet)

**Describe the solution you'd like 🤔**
Well, not sure about this one. Since we can get `hits` and `results`, maybe something like:
```html
<ng-template let-hits="hits" let-results="results" let-facets="facets">
  <div *ngFor="let facet of factes">
    {{facet.count}} <b>{{results.query}}</b> in {{facet.name}}
  </div>
</ng-template>
```

**Describe alternatives you've considered ✨**
If no option available to accomplish this, we'll just write a custom widget.

**Comment by Haroenv** [comment]
If I understand what you want to do correctly, there are some options you can go:

1. call searchForFacetValues on each of your facets

SFFV is a method of the rest api that allows you to search within the values of a facet. This method can be called with the algoliasearch client, but will cost you on search query for each of the facets, per letter, which is thus a lot.

2. change your indexing

If you want to be able to search like this, you could have the following format:

```json
{
   "name": "something",
   "category": "something else"
}
```

Then you can do `distinct` on the category to not show more than one result per "category". This approach won't allow you to put a number on how many results there for that one deduplication. You can read more on that approach here: https://www.algolia.com/doc/guides/managing-results/refine-results/grouping/

3. using query suggestions

The UI you are showing looks a lot like query suggestion, which has the option to suggest categories too. The guide for that is here: https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/query-suggestions/angular/ (although it assumes angular material for the autocomplete, you can switch that out for any other component you already have)

I think the option 3 will fit your needs best. Let me know what you think of those!

**Comment by softmonkeyjapan** [comment]
@Haroenv thanks a lot for your answer. As I just begin with Algolia, I'll take some time to check your answer. In the meantime, I'll try to clarify a bit more about our use case.

First of all, here is how our facet looks like on your dashboard:
<img width="813" alt="Capture d’écran 2019-07-25 à 17 19 48" src="https://user-images.githubusercontent.com/2499912/61858188-9075a280-af00-11e9-8f1d-94e2ce8e699b.png">

The facet section on the left (under `category.name`) is basically what we need to display in our instantsearch box. On your dashboard, if we type a search, this facet is updated in realtime depending on the results (100% what we want). How did you implement it on your dashboard ?

Your API is already returning `facets` as an Object:
<img width="471" alt="Capture d’écran 2019-07-25 à 17 17 48" src="https://user-images.githubusercontent.com/2499912/61858460-11349e80-af01-11e9-965e-20a1007de5aa.png">

So what we tried to do was to access it from the instantSearch. Our best guess was to use `let-results="results"` from:
```html
<ng-template let-results="results">
  <pre>{{results | json}}</pre>
</ng-template>
```
but unfortunately, it doesn't contains the `facets` object, just an empty array called `facets`:
<img width="377" alt="Capture d’écran 2019-07-25 à 17 17 37" src="https://user-images.githubusercontent.com/2499912/61858628-640e5600-af01-11e9-901c-c865b2784387.png">

**Comment by Haroenv** [comment]
If we are only talking about a single facet, you should try out `ais-refinement-list [searchable]="true"`, but likely in custom widget form to fit your UI. More info:

- https://www.algolia.com/doc/api-reference/widgets/refinement-list/angular/
- https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/angular/

**Comment by tkrugg** [comment]
@softmonkeyjapan what you're describing also reminds me of query suggestions:

![image](https://user-images.githubusercontent.com/2982512/64540281-36019b80-d320-11e9-9f6c-5f74a8bce8bf.png)

You can check out the demo here: https://2zn3q1yqx0.csb.app/ and the guide for building it here: https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/query-suggestions/angular/

**Comment by tkrugg** [comment]
Hi  @softmonkeyjapan. I'm closing this for now but feel free to reopen if your problem has not been solved.
