### ISSUE TITLE
ERROR TypeError: Cannot read property 'addAlgoliaAgent' of undefined

### ISSUE THREAD

**Issue by softmonkeyjapan** [algolia/angular-instantsearch#665]
**Describe the bug 🐛**
We spent the last 30 minutes trying to fix this odd bug to finally realize what it was about.

Following the documentation at https://www.algolia.com/doc/guides/building-search-ui/getting-started/angular/?language=javascript#initialization
we realized that the `config` object (the one pass to `<ais-instantsearch [config]="config">`) MUST be pass with a variable call `searchClient`, like in the documentation example:
```js
const searchClient = algoliasearch(
  'B1G2GM9NG0',
  'aadef574be1f9252bb48d4ea09b5cfe5'
);

config = {
  indexName: 'demo_ecommerce',
  searchClient
};
```

If you rename the variable, like we did, to `algoliaClient` for example:
```js
config = {
  indexName: 'demo_ecommerce',
  algoliaClient
};
```

It generates the following errors:
```
ERROR TypeError: Cannot read property 'addAlgoliaAgent' of undefined
ERROR TypeError: Cannot read property 'addWidget' of undefined
```
<img width="1677" alt="Capture d’écran 2019-07-26 à 09 34 45" src="https://user-images.githubusercontent.com/2499912/61917954-7ed8dd00-af8a-11e9-9903-678a165f089d.png">

**To Reproduce 🔍**
Just follow the documentation and replace `searchClient` with `algoliaClient` (or anything else).

Here is a live example of this problem https://codesandbox.io/embed/angular-instantsearch-app-becjl

**Expected behavior 💭**
We should be able to use the naming we want to. Or if this is an intended behavior, it should definitely be explicitly mention somewhere in the doc.

**Environment:**

 - OS: MacOS Mojave 10.14.5
 - Browser Chrome
 - Version 75.0.3770.142 (Build officiel) (64 bits)

**Comment by softmonkeyjapan** [comment]
Ok my bad, just realized the API is talking about it
https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/?language=js#options

Our Typescript/Javascript is a bit limited so we didn't know this:
```js
config = {
  indexName: 'index',
  searchClient
}
```

was same as:
```js
config = {
  indexName: 'index',
  searchClient: object
}
```

**Comment by Haroenv** [comment]
Always nice to learn!
