### ISSUE TITLE
Can't bind to 'config' since it isn't a known property of 'ng-ais-instantsearch'

### ISSUE THREAD

**Issue by ReaperTech** [algolia/angular-instantsearch#670]
**Describe the bug 🐛**
Angular can't find the components although I have imported everything correctly.

error in chrome console "Can't bind to 'config' since it isn't a known property of 'ng-ais-instantsearch'"

**Expected behavior 💭**
Angular should recognize the ais components

**Screenshots 🖥**
![image](https://user-images.githubusercontent.com/43549638/61998249-7f1dc900-b0ad-11e9-84bd-da4b76ae68ae.png)
APP.MODULE
![image](https://user-images.githubusercontent.com/43549638/61998263-c441fb00-b0ad-11e9-80f3-b441f96b321b.png)
![image](https://user-images.githubusercontent.com/43549638/61998285-08350000-b0ae-11e9-84d1-a9e3224813eb.png)
POLYFILLS.TS
![image](https://user-images.githubusercontent.com/43549638/61998503-75966000-b0b1-11e9-8f54-4e3baa6558a7.png)

**Environment:**

 - W10
 - Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

**Comment by ReaperTech** [comment]
solution: was using an old tutorial that had all components prefixed with **ng-** <ng-ais-instantsearch [config]="searchConfig"> . Should be <ais-instantsearch [config]="searchConfig">

**Comment by Haroenv** [comment]
which tutorial was still visible with the old components @ReaperTech?

**Comment by ReaperTech** [comment]
this one.. not one of Algolia's tutorials.
https://angularfirebase.com/lessons/algolia-firestore-quickstart-with-firebase-cloud-functions/

**Comment by Haroenv** [comment]
I've reached out to them, to see if we can get that tutorial updated
