### ISSUE TITLE
How to change the default styling of Algolia search v2.2.2 in Angular 6

### ISSUE THREAD

**Issue by ReaperTech** [algolia/angular-instantsearch#672]
This is the styling I get out the box. There are no instructions in the docs to change the styling? I would like to change the styling to suit my app. The background for instance of the input is white, but I would like to change the color. Is there a way to do it?

![image](https://user-images.githubusercontent.com/43549638/62006191-986e5600-b13d-11e9-8c1b-3142fd24abf0.png)

**Comment by Haroenv** [comment]
Hi @ReaperTech, you can use css to change appearance.

Our default styles are available at:

- "node_modules/angular-instantsearch/bundles/instantsearch.min.css",
- "node_modules/angular-instantsearch/bundles/instantsearch-theme-algolia.min.css",

The classes which are added can be found using the inspector in your browser, e.g. for the input of a search box, that is: `ais-SearchBox-input`

<img width="1005" alt="Screenshot 2019-07-29 at 10 06 16" src="https://user-images.githubusercontent.com/6270048/62031835-8b5a7100-b1e8-11e9-8fa7-7b6396e054f4.png">

Hope that helped you, but feel free to get back here if there's more unclear about styling

**Comment by ReaperTech** [comment]
For anyone trying this with Angular you must put the css in global.scss not component.scss. Dunno why.
Found all the classes in "node_modules/angular-instantsearch/bundles/instantsearch-theme-algolia.css", (you can't read the .min.css version)
example:
global.scss
![image](https://user-images.githubusercontent.com/43549638/62042195-d59a1d00-b1fd-11e9-8302-471e6acbe2a7.png)
![image](https://user-images.githubusercontent.com/43549638/62042244-ed71a100-b1fd-11e9-96d9-6c3a754013d0.png)

**Comment by tkrugg** [comment]
Hi @ReaperTech, note that there is also `node_modules/angular-instantsearch/bundles/instantsearch-theme-algolia.css` (unminified) in the same place.
Feel free to change it, or remove it altogether to use your own style.
