### ISSUE TITLE
searchAsYouType="false" not working v2.2.2

### ISSUE THREAD

**Issue by ReaperTech** [algolia/angular-instantsearch#673]
I am using Angular 6 and want to reduce the operations by using searchAsYouType="false" in the **ais-search-box** so that the user must hit the search icon before a search is initiated, but it is not working. The search still happens as I type??

here is the documentation: https://community.algolia.com/angular-instantsearch/widgets/search-box.html#options

![image](https://user-images.githubusercontent.com/43549638/61999548-daf34c80-b0c3-11e9-9a88-22f9db4e08db.png)

![image](https://user-images.githubusercontent.com/43549638/61999533-99fb3800-b0c3-11e9-892c-9e4354d5e71c.png)

**Comment by Haroenv** [comment]
Hi @ReaperTech, In Angular a value you want evaluated as its JavaScript value, and not as the string value will need to be wrapped in square brackets.

```
<ais-search-box [searchAsYouType]="false"></ais-search-box>
```

A demo of this is available here: https://codesandbox.io/s/angular-instantsearch-app-hjix1

Have a nice day!

**Comment by ReaperTech** [comment]
@Haroenv I have tried square brackets and it still doesn't work, and additionally the highlight function stops working on the <ais-highlight> components. Where can I show you the project?

**Comment by Haroenv** [comment]
You can put your code in a sandbox as well, as minimal as possible, but where the issue still occurs

**Comment by ReaperTech** [comment]
@Haroenv can you use a github repo? I don't know how to use the codesandbox.io
https://github.com/ReaperTech/testalgolia.git
If you can't I will have to find out how to do it....

**Comment by Haroenv** [comment]
One important thing to note is that the `change` event listener will still be called, even if it didn't cause a search with searchAsYouType, is that what you were confused about? 

You should listen to the submit event instead: 

```
  searchChanged(event) {
    const query = event.target.querySelector(".ais-SearchBox-input").value;
    if (query === "") {
      this.showResults = false;
    } else {
      this.showResults = true;
    }
  }
```

https://codesandbox.io/s/angular-instantsearch-app-hjix1

**Comment by ReaperTech** [comment]
@Haroenv thsnks for replying. I want to reduce the operations by using searchAsYouType="false" in the ais-search-box so that the user must hit the search icon before a search is initiated (Algolia charges one operation every time I hit a key). The search still happens as I type even when I use searchAsYouType="false" and [searchAsYouType]="false"  as I have shown in my github repo my the previous reply?

**Comment by ReaperTech** [comment]
@Haroenv I also notice if you don't use the search changed boolean then the whole index appears on the page before you search in the input. Is it downloading the entire index and searching on the client side? What if your index is huge - like 1 million user posts?

**Comment by Haroenv** [comment]
Don't worry, the search happens backend, only matching results are shown to the user. You likely just have a very small index, lower than the "hitsPerPage" limit (default: 20)

With `[searchAsYouType]=false` only required searches as being done, not on every keypress. I just checked it to be sure

**Comment by ReaperTech** [comment]
> Don't worry, the search happens backend, only matching results are shown to the user. You likely just have a very small index, lower than the "hitsPerPage" limit (default: 20)
> 
> With `[searchAsYouType]=false` only required searches as being done, not on every keypress. I just checked it to be sure

Yes my index was only 2 records that's why lol.

Thank you @Haroenv for all your patience and your replies, I've got it working with [searchAsYouType]="false"

**Comment by Haroenv** [comment]
Glad you got everything working!
