### ISSUE TITLE
infinite results

### ISSUE THREAD

**Issue by silverio** [algolia/angular-instantsearch#68]
Hi, I think the show more results button in the infinite results should be optional. In my case, I need to hide it and trigger some how the show more function to bring the next results when the user scrolls to the bottom of the page. Is there a simple way to trigger the show more function without using the button?

**Comment by iam4x** [comment]
Hello @silverio 

Not really for now, you can create a custom widget based on this [guide](https://algolia.gitbooks.io/angular-instantsearch/custom-widgets.html).

But there should be an easy way to load more results, I'll work on that 👍

**Comment by iam4x** [comment]
Hi again @silverio 

I have just release the beta 12 with the templating option fo the show more button.
In the `<ng-template>` directive you can access to the `showMore()` function.

I have updated the doc as example: https://algolia.gitbooks.io/angular-instantsearch/widgets/infinite-hits.html
