### ISSUE TITLE
Loading flag for ais-hits

### ISSUE THREAD

**Issue by Iar0** [algolia/angular-instantsearch#683]
**Is your feature request related to a problem? Please describe 🙏**

I cannot detect if the search of algolia is in progress or not. Using `<ais-hits>`, the hits array is always an empty array. In this way, I cannot distinguish between no results and pending search.

**Describe the solution you'd like 🤔**
Something like
```
<ais-hits>
  <ng-template let-hits="hits" let-results="results">
    <p *ngIf="results.isLoading">loading!</p>
  </ng-template>
</ais-hits>
```

**Describe alternatives you've considered ✨**

I currently know that I always have results for an empty query, so I did `query === '' && hits.length === 0` to show the loading currently. I personally don't like this because it does not really represent the loading

**Comment by Haroenv** [comment]
We have a flag `isSearchStalled`, but it seems like it isn't exposed here, and that would solve your problem. If you use a custom widget, you can access it now: https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/angular/

**Comment by tkrugg** [comment]
If you're looking for a complete example of a custom widget where isSearchStalled is exposed, you can find it here: https://www.algolia.com/doc/api-reference/widgets/search-box/angular/#full-example

**Comment by Iar0** [comment]
thx for the hints! Creating or extending a widget was not necessary, I solved by using the provided instantSearchInstance

```
<ais-hits>
    <ng-template let-hits="hits" let-results="results" let-instantSearchInstance="instantSearchInstance">
        <app-loader *ngIf="instantSearchInstance?._isSearchStalled; else content"></app-loader>
        
        <ng-template #content>
            <app-no-results *ngIf="!hits.length; else dataSection"></app-no-results>

            <ng-template #dataSection>
                <app-results [hits]="hits"></app-results>
            </ng-template> 
        </ng-template>       
    </ng-template>
</ais-hits>
```
