### ISSUE TITLE
Navigation remove query parameters when routing is true

### ISSUE THREAD

**Issue by michelepatrassi** [algolia/angular-instantsearch#691]
**Describe the bug 🐛**

If in the current page ais-instantsearch has a configuration with `routing: true`, then a navigation like the following
```
this.router.navigate(['/'], { queryParams: { foo: 'bar' } });
```
results in the query params being dropped (they are visible in the address bar first, then they get removed).

**To Reproduce 🔍**

Just use a configuration like the following
```
      this.config = {
        searchParameters,
        indexName: this.algoliaParams.index,
        searchClient: this.algoliaService.client,
        numberLocale: 'it',
        routing: true
      };
```
and try to trigger a navigation passing query parameters to the router.navigate method.

**Expected behavior 💭**

Given queryparams remain in the address bar.

**Environment:**

 - OS: mac
 - Browser: chrome

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch). Thanks!

**Comment by tkrugg** [comment]
Hey @michelepatrassi I have reproduced your issue and it is indeed a bug we have, which we'll try to address in https://github.com/algolia/instantsearch.js/issues/4162. 
In the meantime however, you can work around this by disabling InstantSearch URL writing  before triggering your navigation.

Here a code snippet of what I have in mind.

```ts
let defaultRouter = null;

export class SearchComponent {
  config = {
    indexName: "demo_ecommerce",
    searchClient,
    routing: {},
  };
  constructor(private route: ActivatedRoute,   private router: Router, private  location: Location)  {
    defaultRouter = historyRouter({});
    this.config.routing = {
      router: defaultRouter,
    }
  }
  navigate() {
    defaultRouter.write = noop; //  restore it next time the component is instanciated
    this.router.navigate(['/'], { queryParams: { foo: 'bar' } });
  }
}
```

Here is the result:

![2019-10-09 11 32 48](https://user-images.githubusercontent.com/2982512/66469695-994e2d00-ea88-11e9-96d3-04ffcb7fcbeb.gif)
 

I hope this helps in the meantime!
Closing this for now as it's already tracked by https://github.com/algolia/instantsearch.js/issues/4162

**Comment by michelepatrassi** [comment]
cool, thanks @tkrugg (especially for providing the demo, I was postponing it 😅)
