### ISSUE TITLE
Any Options for Angular 8 w/ SSR?

### ISSUE THREAD

**Issue by jrodl3r** [algolia/angular-instantsearch#696]
Spent the last few days setting up a really nice Algolia instant-search solution.... Only to find out that it breaks during Server-Side-Rendering:

```javascript
> npm run serve:ssr
> node dist/server

/svr/node_modules/angular-instantsearch/node_modules/instantsearch.js/es/index.js:2
import algoliasearchHelper from 'algoliasearch-helper';

SyntaxError: Unexpected identifier
```

Is there any way to circumvent or suppress this error during SSR?

For reference, this is the project that we're trying to add this to:
https://github.com/jrodl3r/ng-fire-universal

**Comment by Haroenv** [comment]
This is likely the same issue as here: https://github.com/algolia/angular-instantsearch/issues/687#issuecomment-538274667. Can you try these options?

**Comment by hikeprint** [comment]
@Haroenv Technically, it does get rid of the build error (whitelisting the packages).

However, I can't get it to play well with my existing SRR boilerplate `externals` [see here](https://github.com/jrodl3r/ng-fire-universal/blob/f28156cdae6afea2bb2540639c33c734b91121fb/webpack.server.config.js#L11):

```javascript
externals: [
    { './dist/server/main': 'require("./server/main")' },  // <-- Must comment to avoid InstantSearch error
    nodeExternals({
      whitelist: [
        /^instantsearch.js/,
        /^angular-instantsearch/
      ]
    })
  ],
```

So, in short... I have it working using this guide (https://www.algolia.com/doc/guides/building-search-ui/getting-started/angular/?language=javascript) along with the whitelist fix above.

Funny part is, in commenting that line 🤞(fingers crossed) so far I've not noticed any inverse effects on production yet. I'm no webpack expert, so not sure what type of impact that will have moving forward - Any suggestions on that are greatly appreciated [!!!]

Also, there is an issue with that guide in importing the `algoliasearch/lite` module into `app.component.ts` » You have to add this line to your `tsconfig.json`:

```javascript
"compilerOptions": {
    "allowSyntheticDefaultImports": true,
    ...
```

**Comment by jrodl3r** [comment]
@Haroenv Technically, it does get rid of the build error (whitelisting the packages).

However, I can't get it to play well with my existing SRR boilerplate `externals` [see here](https://github.com/jrodl3r/ng-fire-universal/blob/f28156cdae6afea2bb2540639c33c734b91121fb/webpack.server.config.js#L11):

```javascript
externals: [
    { './dist/server/main': 'require("./server/main")' },  // <-- Must comment to avoid InstantSearch error
    nodeExternals({
      whitelist: [
        /^instantsearch.js/,
        /^angular-instantsearch/
      ]
    })
  ],
```

So, in short... I have it working using this guide (https://www.algolia.com/doc/guides/building-search-ui/getting-started/angular/?language=javascript) along with the whitelist fix above.

Funny part is, in commenting that line 🤞(fingers crossed) so far I've not noticed any inverse effects on production yet. I'm no webpack expert, so not sure what type of impact that will have moving forward - Any suggestions on that are greatly appreciated [!!!]

Also, there is an issue with that guide in importing the `algoliasearch/lite` module into `app.component.ts` » You have to add this line to your `tsconfig.json`:

```javascript
"compilerOptions": {
    "allowSyntheticDefaultImports": true,
    ...
```
