### ISSUE TITLE
"export 'connectSortBy' was not found in 'instantsearch.js/es/connectors'

### ISSUE THREAD

**Issue by Karman40** [algolia/angular-instantsearch#702]
```
import {Component, forwardRef, Inject, Input, OnInit} from '@angular/core';
import {BaseWidget, NgAisInstantSearch} from 'angular-instantsearch';
import {connectSortBy} from 'instantsearch.js/es/connectors';

@Component({
    selector: 'app-ai-mdb-short-by',
    templateUrl: './ai-mdb-short-by.component.html',
    styleUrls: ['./ai-mdb-short-by.component.scss']
})
export class AiMdbShortByComponent extends BaseWidget implements OnInit {
  public state: {
    options: object[];
    currentRefinement: string;
    hasNoResults: boolean;
    refine: any;
    widgetParams: object;
  };

    constructor(
        @Inject(forwardRef(() => NgAisInstantSearch)) public instantSearchParent,
    ) {
        super('SortBy');
    }

    ngOnInit() {
        this.createWidget(connectSortBy, {
            // instance options
            items: [
                {label: 'Featured', value: 'instant_search'},
            ],
        });
        super.ngOnInit();
    }
}
```
```
ERROR in ./src/app/pages/admin/_admin-shared/admin-class/ai-mdb-short-by/ai-mdb-short-by.component.ts 11:26-39
"export 'connectSortBy' was not found in 'instantsearch.js/es/connectors'
```

**Comment by tkrugg** [comment]
Hi @Karman40, could you show us you package.json?
I would like to confirm you have `instantsearch.js@3` installed

**Comment by Karman40** [comment]
Hello @tkrugg !

This package is not installed.
Interesting, because without it all the other (search, refrement list ...) exceptions are short by widget.

**Comment by Karman40** [comment]
@tkrugg 

thanks for the quick response!
Installed with version @3 works well!
happy holidays and thank you for your help :)

**Comment by tkrugg** [comment]
that sounds strange to be because `instantsearch.js` is a peer dependency so you should a least get a warning in your console when your install Angular InstanSsearch. 
I'm glad to see your issue solved. Happy holidays.

**Comment by Karman40** [comment]
There is another issues.

RefinementList

Config:
Limit 10
show more limit 20

About 50 piece

state.canToggleShowMore always return false, and state.toggleShowMore() is not works well

**Comment by Haroenv** [comment]
Have you passed `showMore: true`, as well as the limit @Karman40 ?

**Comment by Karman40** [comment]
Thanks , I don't know why I'm so careless today :(
