### ISSUE TITLE
Console Warning in Beta for instantsearch.js

### ISSUE THREAD

**Issue by asithade** [algolia/angular-instantsearch#709]
*Describe the bug 🐛**
In using angular-instantsearch@3.0.0-beta.4 along with instantsearch.js@^4.1.1, any use of the searching will produce the following warning in console:

```
WARN: '[InstantSearch.js]: The `searchParameters` option is deprecated and will not be supported in InstantSearch.js 4.x.

You can replace it with the `configure` widget:

search.addWidgets([
  configure({
  "highlightPreTag": "__ais-highlight__",
  "highlightPostTag": "__/ais-highlight__"
})
]);

WARN: '[InstantSearch.js]: addWidget will still be supported in 4.x releases, but not further. It is replaced by `addWidgets([widget])`'
```

and 

```
WARN: '[InstantSearch.js]: removeWidget will still be supported in 4.x releases, but not further. It is replaced by `removeWidgets([widget])`'
```

**To Reproduce 🔍**

Follow the steps listed here:
https://www.algolia.com/doc/guides/building-search-ui/installation/angular/

Packages:
    "instantsearch.css": "^7.3.1",
    "instantsearch.js": "^4.1.1",
    "algoliasearch": "^3.35.1",
    "angular-instantsearch": "^3.0.0-beta.4",
    "@types/algoliasearch": "^3.34.8",

**Comment by Haroenv** [comment]
These console warnings come from the underlying libraries. We are currently migrating Angular InstantSearch to InstantSearch v4, however that work is not finished. For now everything should work as expected, and those warnings will not show up in production.
