### ISSUE TITLE
Angular 9 Universal + InstantSearch

### ISSUE THREAD

**Issue by n3nikita** [algolia/angular-instantsearch#723]
**Describe the bug 🐛**

I'm trying to set up Angular 9 Universal application with Angolia Instant Search package. I've used [this guide](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/angular/) but there are some changes at Angular 9 SSR code and files.

Now I'm stuck with this error: 
![image](https://user-images.githubusercontent.com/22433209/79833695-1d745c00-83ac-11ea-8401-fb43d7f070a9.png)

Here's my code:
```typescript
export class BooksComponent {
  config;

  constructor(private title: Title,
              private booksService: BookService,
              private transferState: TransferState,
              private httpClient: HttpClient,
              private injector: Injector,
              @Inject(PLATFORM_ID) private platformId: Object) {
                const req = isPlatformServer(this.platformId) ? this.injector.get('request') : undefined;
                const searchParameters = parseServerRequest(req);
                const searchClient = createSSRSearchClient({
                  makeStateKey,
                  HttpHeaders,
                  transferState: this.transferState,
                  httpClient: this.httpClient,
                  appId: '...',
                  apiKey: '...',
                });

                this.config = {
                  indexName: 'books',
                  routing: false,
                  searchClient,
                  searchParameters
                }
              }
}

```

**Comment by eunjae-lee** [comment]
Hi @n3nikita,
It's hard to figure out what the problem is from the error log.
It seems related to firebase or whatnot.
Could you share more error logs or preferably a minimal reproducible example?

**Comment by n3nikita** [comment]
Hello
I figured out why did I have this problem.

Google Cloud functions can't access my config variables so I created  `.runtimeconfig.json` with the following data:
```json
{
  "algolia": {
    "key": "...",
    "app": "..."
  }
}
```

If you are trying to test your functions before you deploy, here is the link to the documentation on how to do it: https://firebase.google.com/docs/functions/local-emulator

**Comment by eunjae-lee** [comment]
Thanks for sharing!
Have a nice day :)
