### ISSUE TITLE
ionic + voice search

### ISSUE THREAD

**Issue by geraldmichl** [algolia/angular-instantsearch#726]
Hi folks, 
I am trying to get the voice search working with ionic. The problem is that when the voice recognition button (<ais-voice-search>) is touched, the keyboard appears and the app does not start to listen to voice input. How can this be achieved? 
As stated [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/native/angular/) there should be no differences to the web version.

**Comment by francoischalifour** [comment]
Are you able to check the console for logs?

The voice search widget makes use of the [SpeechRecognition Web API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) which might not be available on Ionic.

**Comment by geraldmichl** [comment]
Thank you for your quick reply!

The logs do not indicate anything. Seems like the keyboard acts as natural fallback for the SpeechRecognition Web API.

**Comment by francoischalifour** [comment]
Could you please share with us a minimal reproduction?

**Comment by geraldmichl** [comment]
By trying to provide an example I figured out that the actual problem is that no microphone permission request is triggered for Ionic apps. When setting the permission manually in the android settings everything works as expected.

**Comment by francoischalifour** [comment]
Sounds good—thanks for letting us know.
