### ISSUE TITLE
Getting warning with v2.3.0 with Angular 9.1.3

### ISSUE THREAD

**Issue by Shashanka8** [algolia/angular-instantsearch#731]
Getting ''Entry point 'angular-instantsearch' contains deep imports into //path_to_module.. This is probably not a problem, but may cause the compilation of entry points to be out of order."

How to deal with it?

**Comment by Haroenv** [comment]
Since this is just a warning (not an error), you can simply ignore it. However, I do not see that on the demo application. Could you create a GitHub example which shows this warning?
