### ISSUE TITLE
ais-sort-by Index ... not present in `indices`

### ISSUE THREAD

**Issue by Karman40** [algolia/angular-instantsearch#732]
**Describe the bug 🐛**

A want to add sort-by options but, when i add <ais-sort-by> a get error. 

![image](https://user-images.githubusercontent.com/32225709/85576991-28ac6800-b639-11ea-814a-ac6fcd409936.png)

```
<ais-sort-by
  [items]="[
    { name: 'instant_search', label: 'Featured' },
    { name: 'instant_search_price_asc', label: 'Price asc.' },
    { name: 'instant_search_price_desc', label: 'Price desc.' },
  ]"
>
</ais-sort-by>
```

and the docs bad, becouse docs say { VALUE: ... }[] but i need to use { name: ... }
https://www.algolia.com/doc/api-reference/widgets/sort-by/angular/

**Comment by eunjae-lee** [comment]
Hi there, thanks for reporting the error.
You're right. I'll update the doc soon.

```
<ais-sort-by
  [items]="[
    { name: 'instant_search', label: 'Featured' },
    { name: 'instant_search_price_asc', label: 'Price asc.' },
    { name: 'instant_search_price_desc', label: 'Price desc.' }
  ]"
>
</ais-sort-by>
```

In the meantime, you can use the snippet above. Again there was a mistake with the comma in the last item in the array.

**Comment by eunjae-lee** [comment]
Hi @Karman40 
Thanks for reporting the issue.
I guess you're using Angular InstantSearch@v2.

In v3 (which is beta now), `name` gets renamed to `value`.
You can learn more [here](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/angular/#sortby-items-property-changed).

And the doc you were looking at is for v3.

About that, you need to remove the comma in the last item in the array. I will update the doc to fix it.

```diff
<ais-sort-by
  [items]="[
    { name: 'instant_search', label: 'Featured' },
    { name: 'instant_search_price_asc', label: 'Price asc.' },
-    { name: 'instant_search_price_desc', label: 'Price desc.' },
+    { name: 'instant_search_price_desc', label: 'Price desc.' }
  ]"
>
</ais-sort-by>
```

**Comment by Karman40** [comment]
i use: `angular-instantsearch`: `^2.3.0`,

That's fine, but it doesn't work with V2 yet.
