### ISSUE TITLE
:class-names not being applied to ais-pagination

### ISSUE THREAD

**Issue by natetwo** [algolia/angular-instantsearch#734]
**Describe the bug 🐛**
When using ":class-names", custom class names are not applied to the html elements.
Using sample markup from: https://www.algolia.com/doc/api-reference/widgets/pagination/angular/#widget-param-class-names

**To Reproduce 🔍**
Using angular instant search, apply some custom class names to the pagination element, such as:
```
<ais-pagination
  :class-names="{
    'ais-Pagination': 'MyCustomPagination',
    'ais-Pagination-list': 'MyCustomPaginationList',
  }"
></ais-pagination>

```

Live code example:
https://codesandbox.io/s/ais-pagination-class-names-issue-fmovg?file=/src/app/app.component.html

**Expected behavior 💭**
Expected elements with 'ais-Pagination' & 'ais-Pagination-list' classes to have 'MyCustomPagination" & 'MyCustomPaginationList' classes added to them, respectively.

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/32465653/87248044-ee0a4400-c41c-11ea-848a-7a1e76fe28f4.png)

**Environment:**

 - OS:Mac
 - Browser: Chrome
 - Version Version 83.0.4103.116

**Comment by eunjae-lee** [comment]
Hi @natetwo ,
I'm sorry, the documentation was wrong. We do not provide `:class-names` props in Angular InstantSearch. It must've been copied&pasted wrongly from Vue InstantSearch.

At the moment, you need to use the widget as is, or create a custom widget [by using the connector](https://www.algolia.com/doc/api-reference/widgets/pagination/angular/#connector).

Sorry for the confusion.

By the way, the documentation you're reading is for angular-instantsearch@v3, but in your code sandbox, you're using v2.
For your information, you can read [the doc for v2 here](https://community.algolia.com/angular-instantsearch/getting-started), but we recommend you to use v3 if you can. And [this](https://codesandbox.io/s/ais-pagination-class-names-issue-5hub6?file=/src/app/app.component.html) is an updated sandbox to v3.

**Comment by natetwo** [comment]
Bummer. Thanks for letting me know.

By the way, I was using the code sandbox recommended in the issue template, it must be referencing that version, by default.
