### ISSUE TITLE
RefinementList extended widget - 'X' is not a retrieved facet.

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [algolia/angular-instantsearch#736]
Hi,
I'am trying to extend `RefinementList` widget as documented here : https://www.algolia.com/doc/api-reference/widgets/refinement-list/angular/#full-example.
I getting `Error: X is not a retrieved facet.` , Although it works properly with the built-in widget.
So 
`<ais-refinement-list attribute="X"></ais-refinement-list>` -> Works

But  the following does not work.
```
 ngOnInit(): void {
    this.createWidget(connectRefinementList, {
      // instance options
      attribute: 'X',
      
    });
    super.ngOnInit();
  }
```
Be noted that I Added `X` for **Attributes for faceting** in my dashboard and make it searchable. 

My `package.json` : 
```
...
"@angular/core": "^9.0.0",
"algoliasearch": "^3.35.1",
"angular-instantsearch": "^2.3.0",
"instantsearch.css": "^7.4.2",
"instantsearch.js": "^4.7.0",
"@types/algoliasearch": "^3.34.10",
...
```
What's wrong in my code?

**Comment by Haroenv** [comment]
This indeed should work, however Angular InstantSearch v2 is compatible with InstantSearch v2, and not with InstantSearch.js v4 as you've used. Is it possible to recreate this in a sandbox or similar?

**Comment by waseem-isaac-BBN** [comment]
@Haroenv 
Other functionalities work properly for me. However i'll try to downgrade InstantSearch.js version.

**Comment by eunjae-lee** [comment]
@waseem-isaac-BBN 
https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch?file=/package.json

This is a working sandbox. You can refer to the versions used there. And if it still doesn't work, we'd appreciate if you put some code in the sandbox for reproduction :)

**Comment by waseem-isaac-BBN** [comment]
@eunjae-lee 
It doesn't include `instantsearch.js` package for extending the widgets :))

**Comment by waseem-isaac-BBN** [comment]
> This indeed should work, however Angular InstantSearch v2 is compatible with InstantSearch v2, and not with InstantSearch.js v4 as you've used. Is it possible to recreate this in a sandbox or similar?

I downgraded  to InstantSearch.js@3 and it didn't work too ., do you know a specific version number of that package which has a compatible connectRefinementList with the mentioned versions ? @Haroenv

**Comment by waseem-isaac-BBN** [comment]
@Haroenv 
That's a part of `renderOptions` object which returned in `return {  render: function render(renderOptions)  .. } }` in `connectRefinementList.js` file (instantSearch.js@4). 
`facets` shouldn't be an empty array !? 
I added the attribute in `Indices>>Configuration>>FILTERING AND FACETING>>Attributes` for faceting in Dashboard
Am I correct or there another way for adding the attribute?

```
..
instantSearchInstance: InstantSearch {_events: {…}, _eventsCount: 1, _maxListeners: undefined, client: AlgoliaSearchBrowser, helper: AlgoliaSearchHelper, …}
results: SearchResults
aroundLatLng: undefined
automaticRadius: undefined
disjunctiveFacets: []
exhaustiveFacetsCount: undefined
exhaustiveNbHits: true
facets: []
hierarchicalFacets: []
hits: (20) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
hitsPerPage: 20
.....
```

**Comment by Haroenv** [comment]
I don't think the index configuration is an issue, but if you have a doubt, you can use the one from the demo

**Comment by eunjae-lee** [comment]
Hey @Haroenv If I'm not mistaken, [Angular InstantSearch v2 works with InstantSearch v2](https://github.com/algolia/angular-instantsearch/blob/master/package.json#L96:L96), no?

@waseem-isaac-BBN InstantSearch.js is already included as a dependency inside Angular InstantSearch. So you don't have to include it again.

https://codesandbox.io/s/happy-mclean-ots8e?file=/src/app/refinement-list.ts

Here is an example I made for you. I created a custom refinementList component.

**Comment by waseem-isaac-BBN** [comment]
> Hey @Haroenv If I'm not mistaken, [Angular InstantSearch v2 works with InstantSearch v2](https://github.com/algolia/angular-instantsearch/blob/master/package.json#L96:L96), no?
> 
> @waseem-isaac-BBN InstantSearch.js is already included as a dependency inside Angular InstantSearch. So you don't have to include it again.
> 
> https://codesandbox.io/s/happy-mclean-ots8e?file=/src/app/refinement-list.ts
> 
> Here is an example I made for you. I created a custom refinementList component.

connectRefinementList is imported form `instantsearch.js/es/connectors` not "angular-instantsearch"  as https://codesandbox.io/s/happy-mclean-ots8e?file=/src/app/refinement-list.ts:135-207 says in  Line 3 

Thanks, I will try to use these exact versions for my code

**Comment by waseem-isaac-BBN** [comment]
It works now . the data rendered but the error msg `taxons is not a retrieved facet.` still appears randomly.

**Comment by Haroenv** [comment]
Is that an actual error, or just a warning @waseem-isaac-BBN? If it's a warning, and the app actually works, that's a known issue for these versions, which has been fixed in later versions and you can safely ignore

**Comment by waseem-isaac-BBN** [comment]
@Haroenv 
It's an error as u can see in the attached image. its weird to appear randomly although the data rendered . Because of that I think there was an issue with my account index configuration (dashboard).
![image](https://user-images.githubusercontent.com/45534453/87957531-b0f32100-cab0-11ea-8c1c-7c5378e4650c.png)

**Comment by Haroenv** [comment]
This is actually a subtle error based on network speed and has nothing to do with the account configuration. Unfortunately you can't change it, unless you patch `getFacetValues` (like has been done in algoliasearch-helper@3). Since the error has no impact on the page, you can leave it be

**Comment by waseem-isaac-BBN** [comment]
> This is actually a subtle error based on network speed and has nothing to do with the account configuration. Unfortunately you can't change it, unless you patch `getFacetValues` (like has been done in algoliasearch-helper@3). Since the error has no impact on the page, you can leave it be

Yes, It can be a network issue

**Comment by waseem-isaac-BBN** [comment]
> This is actually a subtle error based on network speed and has nothing to do with the account configuration. Unfortunately you can't change it, unless you patch `getFacetValues` (like has been done in algoliasearch-helper@3). Since the error has no impact on the page, you can leave it be

@Haroenv Hello ,
How can I patch getFacetValues (for angular +2) ?
As u mentioned `(like has been done in algoliasearch-helper@3)"` , is there a reference/doc. for that ?

**Comment by waseem-isaac-BBN** [comment]
> @Haroenv
> It's an error as u can see in the attached image. its weird to appear randomly although the data rendered . Because of that I think there is an issue with my account index configuration (dashboard).
> ![image](https://user-images.githubusercontent.com/45534453/87957531-b0f32100-cab0-11ea-8c1c-7c5378e4650c.png)

I think that's the same case of https://github.com/algolia/angular-instantsearch/issues/99

**Comment by waseem-isaac-BBN** [comment]
in `node_modules/algoliasearch-helper/src/SearchResults/index.js.SearchResults.getFacetValues` Line 645
Why not doing the fallback value for `facetValues` like below ? 
```
SearchResults.prototype.getFacetValues = function(attribute, opts) {
  var facetValues = extractNormalizedFacetValues(this, attribute) || [];  // this prevent the error messages from appearin
  if (!facetValues) throw new Error(attribute + ' is not a retrieved facet.');
 ...
```

**Versions**
    "algoliasearch": "3.33.0",
    "angular-instantsearch": "3.0.0-beta.2",
    "instantsearch.js": "3.7.0",
    "@types/algoliasearch": "3.30.13",

**Comment by waseem-isaac-BBN** [comment]
It fixed after using the latest version of `instantsearch.js@^4.7.0`  :))
