### ISSUE TITLE
Doesnt Work with Angular 10.0.4

### ISSUE THREAD

**Issue by juanjinario** [algolia/angular-instantsearch#738]
I was unable to update my Angular project to version 10 because angular-instantsearch does not allow it.
The versions that I have installed are:

```
  "algoliasearch": "^3.35.1",
    "angular-instantsearch": "^3.0.0-beta.5",
    "instantsearch.js": "^4.6.0",
```

**Comment by eunjae-lee** [comment]
Hi @juanjinario ,
I'm sorry that you're having a trouble with Angular InstantSearch and Angular 10.
To be honest, we haven't properly investigated on the support for Angular 10.
I hope we can come up with it soon, but I'm afraid we cannot estimate the time yet.

Could you log what you faced there? It will be helpful when we get into it.

**Comment by juanjinario** [comment]
I receive this error messages: @eunjae-lee 

```
Package "angular-instantsearch" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0 <9.0.0" (extended), would install "10.0.5").
                  Package "angular-instantsearch" has an incompatible peer dependency to "@angular/common" 
(requires ">=5.0.0 <9.0.0" (extended), would install "10.0.5").
                  Package "angular-instantsearch" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=5.0.0 <9.0.0" (extended), would install "10.0.5").
                  Package "angular-instantsearch" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires ">=5.0.0 <9.0.0" (extended), would install "10.0.5").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
-browser-dynamic" (requires ">=5.0.0 <9.0.0" (extended), would install "10.0.5").
```


I can force update with the --force flag, but I don't know if something will be damaged, I need to know if everything will work fine

**Comment by Haroenv** [comment]
This is just a warning, which is in place, since we officially only support up until angular 8. If you actually install it with --force, do you receive any errors?

**Comment by juanjinario** [comment]
We only use the Angular-instasearch widget, which could work at the moment, I need the guarantee that all the features of Algolia will work in the future and that I will not have to return from Angular version. I cannot do a test on my production project.

**Comment by abzalzhumabaev** [comment]
```bash
ERROR in node_modules/angular-instantsearch/instantsearch/instantsearch.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
    
    3     static forRoot(): ModuleWithProviders;
                            ~~~~~~~~~~~~~~~~~~~
    node_modules/angular-instantsearch/index.d.ts:63:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
```
How to ignore it, or what I should do ?)

**Comment by Haroenv** [comment]
@abzalzhumabaev, this one seems difficult to keep supporting older versions (pre Angular 7)

see: https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic

A solution for now should be to use https://angular.io/guide/glossary#ngcc, or if that doesn't work, something like [patch-package](https://github.com/ds300/patch-package) to change:

```
import { CommonModule } from '@angular/common';
import { ModuleWithProviders, NgModule } from '@angular/core';

import { NgAisInstantSearch } from './instantsearch';

@NgModule({
  declarations: [NgAisInstantSearch],
  entryComponents: [NgAisInstantSearch],
  exports: [NgAisInstantSearch],
  imports: [CommonModule],
})
export class NgAisInstantSearchModule {
  public static forRoot(): ModuleWithProviders {
    return {
      ngModule: NgAisInstantSearchModule,
      providers: [],
    };
  }
}
````

to:

```
import { CommonModule } from '@angular/common';
import { ModuleWithProviders, NgModule } from '@angular/core';

import { NgAisInstantSearch } from './instantsearch';

@NgModule({
  declarations: [NgAisInstantSearch],
  entryComponents: [NgAisInstantSearch],
  exports: [NgAisInstantSearch],
  imports: [CommonModule],
})
export class NgAisInstantSearchModule {
  public static forRoot(): ModuleWithProviders<NgAisInstantSearchModule> {
    return {
      ngModule: NgAisInstantSearchModule,
      providers: [],
    };
  }
}
```

**Comment by ictus4u** [comment]
I got these warnings after `npm install`, with `ngcc` as postinstall task:
```
npm WARN angular-instantsearch@2.3.0 requires a peer of @angular/common@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-instantsearch@2.3.0 requires a peer of @angular/core@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-instantsearch@2.3.0 requires a peer of @angular/platform-browser@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-instantsearch@2.3.0 requires a peer of @angular/platform-browser-dynamic@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
```

Environment:
```
Angular CLI: 10.1.2
Node: 12.18.4
OS: linux x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes
```

**Comment by Haroenv** [comment]
@ictus4u, those seem like warnings, and not errors. Does it actually not work or just print the warning? 

Note also that you probably want to use `angular-instantsearch@beta`

**Comment by aldric** [comment]
Hello guys. Still no plan to upgrade to Angular 10+ ? It would be really appreciated .
Thanks

**Comment by michelepatrassi** [comment]
using v3.0.0-beta.5 with angular 10.1.5 for a side project with a search functionality, no problem so far. I'm actually going to give a try to angular 11

**Comment by eunjae-lee** [comment]
https://github.com/eunjae-lee/my-angular11-app

I made this simple example with angular 11 + angular InstantSearch@beta.
Can you see if it works for you?

**Comment by keduardo2117** [comment]
I force updated to angular 11.1.2 and the instant search is working for me. 

Is this project still maintained? It's been almost a year since the last release.

**Comment by ramikhafagi96** [comment]
Is there any plan to start supporting Angular10+? it is really needed.
Thanks

**Comment by francoischalifour** [comment]
Hey all! The latest contributions happen on the [`v4`](https://github.com/algolia/angular-instantsearch/blob/v4/) branch, which is why the `master` branch might feel left behind.

We're in the process of planning our priorities for the coming months and we'll provide official support for Angular 10+.

**Comment by mwawrusch** [comment]
That link 404s. Still can't get 2.3 or 3.0 to work in our existing large angular app...

**Comment by ramikhafagi96** [comment]
> Hey all! The latest contributions happen on the [`v4`](https://github.com/algolia/angular-instantsearch/blob/v4/) branch, which is why the `master` branch might feel left behind.
> 
> We're in the process of planning our priorities for the coming months and we'll provide official support for Angular 10+.

Should we install the package using the `v4` branch to avoid issues in Angular 10+ ?

**Comment by francoischalifour** [comment]
We've released [`4.0.0-alpha.0`](https://www.npmjs.com/package/angular-instantsearch/v/4.0.0-alpha.0) which brings basic support for Angular 10+. We'll release on this `alpha` tag for further improvements.

You can install it now:

```sh
npm install angular-instantsearch@4.0.0-alpha.0
# or
yarn add angular-instantsearch@4.0.0-alpha.0
```

Please feel free to [open issues](https://github.com/algolia/angular-instantsearch/issues/new?assignees=&labels=&template=BUG_REPORT.md) for any bug you may encounter.

**Comment by jugglingthebits** [comment]
@francoischalifour just so I understand the plan here - is v3 the next version to be released as stable, or is it v4? Both are in beta/alpha currently it seems, and the v4 branch is behind the v3 one.

**Comment by francoischalifour** [comment]
Long term, v4 (which is currently alpha) will provide support for Angular 10+, so it'll be the version we'll release stable in the future.

**Comment by somehan** [comment]
similar issue: https://github.com/algolia/angular-instantsearch/issues/813

**Comment by cam424** [comment]
angular-instantsearch@4.0.0-alpha.0 still requires a peer dependency of @angular/common of < 9.0.0 so like ¯\_(ツ)_/¯

**Comment by tkrugg** [comment]
@cam424 please use alpha.1

**Comment by ramikhafagi96** [comment]
@tkrugg how to install it with npm please?

**Comment by Haroenv** [comment]
`npm install angular-instantsearch@4.0.0-alpha.1` @ramikhafagi96 :)

**Comment by twawrzyczny** [comment]
I've tried importing both 4.0.0-alpha.1 and 4.0.0-alpha.2 and both are giving me this error on build:

ERROR in ./node_modules/angular-instantsearch/fesm2015/angular-instantsearch.js
Module not found: Error: Can't resolve 'algoliasearch/lite' in 'C:\projects\stash\web\node_modules\angular-instantsearch\fesm2015'
 @ ./node_modules/angular-instantsearch/fesm2015/angular-instantsearch.js 4:0-57 99:24-50 99:54-72 2547:30-56 2548:6-32 2549:6-24
 @ ./js/app/components2/search-box/search-box.component.ts
 @ ./js/app/components2/components.module.ts
 @ ./js/app/modules/app.module.ts
 @ ./js/app/modules/preApp.module.js
 @ ./js/app/app-scripts.ts

ERROR in C:/projects/stash/cinemaweb7-v2/Cinema.Web/node_modules/angular-instantsearch/create-ssr-search-client.d.ts
ERROR in C:/projects/stash/cinemaweb7-v2/Cinema.Web/node_modules/angular-instantsearch/create-ssr-search-client.d.ts(13,174):
TS2694: Namespace 'algoliasearch' has no exported member 'SearchClient'.

**Comment by Haroenv** [comment]
@twawrzyczny what's in your package.json? Do you have `algoliasearch@4` installed?

**Comment by tkrugg** [comment]
@twawrzyczny closing. if you're still experiencing issues feel free to reopen.
