### ISSUE TITLE
Render nested attributes for faceting dynamically 

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [algolia/angular-instantsearch#739]
I am trying to find out the possibility of the following :

Consider I have an object `taxons : {main : 'taxon1' , other : 'taxons2'}`
Is there any way to render the list of taxons **dynamically** like looping through that list ?
instead of typing `<ais-refinement-list attribute="taxons.main"></ais-refinement-list>` and another element for `taxons.other`

**Comment by Haroenv** [comment]
Do you statically know which filters are available, or does this depend on the result?

**Comment by waseem-isaac-BBN** [comment]
@Haroenv No I don't , Not for all of them.

**Comment by Haroenv** [comment]
Could you clarify what defines the facets, is it dependent on the current results, any result, or global?

Note that it's not possible to have a wildcard of facets to enable for faceting, so you should have that in the dashboard already

**Comment by waseem-isaac-BBN** [comment]
@Haroenv 
The nested attributes are pre-defined statically in the dashboard too . And I was asking about that to.
 "I only be able to render (statically) the facets which were pre-defined and selected in the dashboard." 
 no way of doing otherwise ?

**Comment by Haroenv** [comment]
Out of the box, not that I know of, but if you explain your full use case / expected UI, we can help suggest a different way to achieve it
