### ISSUE TITLE
Do you have example of using createAlgoliaClient to clear the cache?

### ISSUE THREAD

**Issue by shrestaz** [algolia/angular-instantsearch#76]
I am trying to programmatically update the cache in my component. 

**Html**
```html
<button (click)="updateCache()">update<button>
<ng-ais-instantsearch [config]="algoliaEnv" >
<ng-ais-search-box></ng-ais-search-box>
<ng-ais-hits></ng-ais-hits>
```
**Component**
```javascript
this.algoliaEnv = {
      apiKey: <api-key>,
      appId: <app-id>,
      indexName: <index-name>,
      createAlgoliaClient: this.testFunction,
};

testFunction(customClient: Function, appId: string, apiKey: string) {
  // How do I use customClient here ?
  const algoliaSearch: algoliasearch.AlgoliaClient = customClient(appId, apiKey);
  return algoliaSearch;
}

updateCache(){
  // What should I call here?
}
```
The above code does _not_ throw any errors, but I am trying to figure out how to update the cache programmatically, for example inside the updateCache method.
The documentation states: "We forward algoliasearch which is the original algoliasearch module imported inside angular-instantsearch." - but how do I use this?

I really hope you can help me out here :)

**Comment by Haroenv** [comment]
I didn't create AIS, but @iam4x is currently in a different timezone, but you should be able to [create a custom widget](https://algolia.gitbooks.io/angular-instantsearch/custom-widgets.html) and have access to the instantsearch instance, after which you can call the `.refresh` method on it

**Comment by shrestaz** [comment]
Thanks. I'll try that.

**Comment by shrestaz** [comment]
@Haroenv I created a custom widget following the guide you linked to. So, should I call the `.refresh` method like the following?
```javascript
this.instantSearchParent.refresh();
```

**Comment by Haroenv** [comment]
That should work! If you have any troubles with it, please make a codesandbox (template [here](https://codesandbox.io/s/8x27p025ml)) with what you tried and how it doesn't work.

**Comment by shrestaz** [comment]
I tried to replicate creating a custom widget on codesandbox [**here**](https://codesandbox.io/s/wzq0yj51q5). Basically, a new component  named `custom-widget` has been created, following the guide.

On the app.component template, when I try to insert my custom widget like following
```html
<ng-ais-instantsearch>
....
<custom-widget></custom-widget>
....
</ng-ais-instantsearch>
```
The browser crashes as soon as I close the custom widget `</custom-widget>`.

As for when I replicate the same on an IDE, I get this error
```
this.instantSearchParent.clearCache is not a function
```

Also, thank you for taking your time to help :100:

**Comment by Haroenv** [comment]
You were almost there, the function is called `refresh` and is on the `instantSearchInstance`, and you also need to implement the button in your app. 

I forked your sandbox: [here](https://codesandbox.io/s/p3978nj2oq) is my version with the necessary changes.

**Comment by brunoFreiberger** [comment]
Hi, i need clear the cache, but i'm getting this error:

`AppComponent.html:87 ERROR TypeError: Cannot read property 'render' of undefined
    at InstantSearch.js:200
    at Array.forEach (<anonymous>)
    at InstantSearch.addWidgets (InstantSearch.js:198)
    at InstantSearch.addWidget (InstantSearch.js:178)
    at NgAisInstantSearch.webpackJsonp.../../../../angular-instantsearch/bundles/angular-instantsearch.esm.js.NgAisInstantSearch.addWidget (angular-instantsearch.esm.js:131)
    at CustomWidgetComponent.webpackJsonp.../../../../angular-instantsearch/bundles/angular-instantsearch.esm.js.BaseWidget.ngOnInit (angular-instantsearch.esm.js:61)
    at CustomWidgetComponent.webpackJsonp.../../../../../src/app/custom-widget/custom-widget.component.ts.CustomWidgetComponent.ngOnInit (custom-widget.component.ts:28)
    at checkAndUpdateDirectiveInline (core.es5.js:10843)
    at checkAndUpdateNodeInline (core.es5.js:12341)
    at checkAndUpdateNode (core.es5.js:12284)`

This error is happening even when i run the project you posted above

**Comment by Haroenv** [comment]
Hey @brunoFreiberger, I don't seem to have that problem, is that on a specific browser and consistently?

**Comment by brunoFreiberger** [comment]
@Haroenv, I'm using chrome and i just download the project of your sandbox link. Any idea what that might be?

**Comment by Haroenv** [comment]
No I don't know what could be the problem in that error since I don't get it, but what I suggest doing is following the [getting started](https://community.algolia.com/angular-instantsearch/getting-started.html) guide, and doing the modifications I did in the earlier comment. If you have an issue with that too, please open a new isssue

**Comment by brunoFreiberger** [comment]
I used code of your comment and now it's working, thank you!

**Comment by Haroenv** [comment]
perfect, something odd must have gone wrong with that demo / codesandbox then :)
