### ISSUE TITLE
Restrict searchable attributes

### ISSUE THREAD

**Issue by silverio** [algolia/angular-instantsearch#78]
Hi,

Can I restrict searchable attributes with angular-instantsearch? I found an [example](https://www.algolia.com/doc/tutorials/full-text-search/multi-language-search/multilingual-search/?language=node#option-2-each-record-contains-all-languages) with Algolia’s Javascript Helper. Do I have to import this library to my project, or is there a way to do this with the angular-instaseacrh library? are there any examples available?

Thanks!

**Comment by Haroenv** [comment]
```html
<ng-ais-instantsearch
      [config]="{
        apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
        appId: 'latency',
        indexName: 'instant_search',
        searchParameters: {
         restrictSearchableAttributes: ['something']
        }
      }"
    >
    </ng-ais-instantsearch>
```

You can also set up `searchableAttributes` in `index.setSettings({searchableAttributes: ['thing']})`, which will apply that globally. See also [the documentation of the restrictSearchableAttributes parameter](https://www.algolia.com/doc/api-reference/api-parameters/restrictSearchableAttributes/?language=javascript#search-on-a-restricted-set-of-attributes) and [the searchableAttributes parameter](https://www.algolia.com/doc/api-reference/api-parameters/searchableAttributes/)
