### ISSUE TITLE
facets in a separate page

### ISSUE THREAD

**Issue by silverio** [algolia/angular-instantsearch#79]
Hi,

I got the facets working on the same page as the searchbar and the results. But I want to have the facets in a different page as shown in the gif.  Any tips on how to do this? 

Thanks!

![Alt Text](https://media.giphy.com/media/4YY9dYp62P9hPp6WOs/giphy.gif)

**Comment by iam4x** [comment]
Hello @silverio,

I don't really understand where you have another page on the gif, is it the top right menu?

If yes, I would recommend to better display your menu as a modal than another page it would be easier.

**Comment by silverio** [comment]
hello @iam4x ,

I am using Ionic for my project, when I said pages I meant a component that will act as an entire view. So, in my project I have 2 views **search** and **popover-filter**.

The search view has 2 custom widgets:
1.  `<alg-search></alg-search>` which is is the same `<ng-ais-search-box></ng-ais-search-box>` but with ionic's search-box.

2.  `<alg-facets attribute="variant_en.color" limit="10"></alg-facets>` which is the same `<ng-ais-refinement-list></ng-ais-refinement-list>` but with ion-item html tags.

**search.html**
```<ion-header>

  <ion-navbar>
    <ion-title>Search</ion-title>
    <ion-buttons right>
      <button ion-button icon-only (click)="presentPopover($event)">
        <ion-icon name="md-more"></ion-icon>
      </button>
    </ion-buttons>
  </ion-navbar>

</ion-header>


<ion-content>
  <ng-ais-instantsearch [config]="{
    apiKey: 'xxxxxxxxxx',
    appId: 'xxxxxxxx',
    indexName: 'xxxxxx

  }">
    <alg-search></alg-search>

    <alg-facets attribute="variant_en.color" limit="10"></alg-facets>

    <ng-ais-infinite-hits>
      <ng-template let-hits="hits" let-results="results">
        <div *ngIf="hits.length === 0">
          No results found matching
          <strong>{{results.query}}</strong>.
        </div>
        <ion-list>
          <ion-item *ngFor="let hit of hits">
            <ion-thumbnail item-start>
              <img [src]=imgURL+hit.image+resizeParamsAvatar>
            </ion-thumbnail>
            <h2>
              <ng-ais-highlight [attributeName]="search" [hit]="hit">
              </ng-ais-highlight>
            </h2>
            <p>{{hit.brandName}}</p>
            <p>Price {{hit.price}}</p>
            <button ion-button clear item-end>View</button>
          </ion-item>
        </ion-list>
      </ng-template>
    </ng-ais-infinite-hits>
  </ng-ais-instantsearch>
</ion-content>
```

I want the facets widget `<alg-facets attribute="variant_en.color" limit="10"></alg-facets>`  in a different view, which is opened using the button in the top right corner. Ionic opens modals and popovers using an entire new view, so thats why I am using the second page/view **popover-filter**.
So my question is, how can I make the `<alg-facets>` widget in the  **popover-filter** view, interact with the hits of of the search view.

**Comment by iam4x** [comment]
Hi @silverio 

Sorry for the late answer, I have been taking some time to think about your issue but I still do not have an easy solution for you.

At first this use-case was possible, but some users requested the possibility to mount multiple search instances on the same page, so now you cannot reference a same instance from a different page.

What I have in mind is for you to create a custom widget which save the instantsearch instance into an Angular Service that you can access from a different "page"

Does that makes sense for you? Or would you need a guide on how to achieve this?

**Comment by iam4x** [comment]
Closing since it did not have any activity for two months. Feel free to answer back if help is needed here @silverio

**Comment by Blast06** [comment]
Hi @silverio , can you help me yo integrate algolia on my ionic project, cause, i followed the Angular Instantsearch tutorial, but i couldnt do it, how did you do it?
