### ISSUE TITLE
infinite-hits - show previous pages results

### ISSUE THREAD

**Issue by kamilo81** [algolia/angular-instantsearch#80]
My initial page params: ?q=&idx=items&p=2
it shows me only results from page 2 and i can not show result form page 1 and page 0.
I dont want to use pagination. Im only using infinite-hits with show more button.

There is a way to show results from p0 to p2 ?

**Comment by iam4x** [comment]
Hi @kamilo81 let's keep the discussion into: https://github.com/algolia/instantsearch.js/issues/2750

We would need to implement this behaviour into InstantSearch.js before having it into Angular InstantSearch.

**Comment by kamilo81** [comment]
Ok
