### ISSUE TITLE
ais-range-slider missing implementation of tooltips

### ISSUE THREAD

**Issue by Celtian** [algolia/angular-instantsearch#805]
**Is your feature request related to a problem? Please describe 🙏**

I would like to format tooltips. E.g. currencies, separator (coma or dot, or ...).

In this library it is possible. (can be boolean or object)
https://www.algolia.com/doc/api-reference/widgets/range-slider/js/#widget-param-tooltips

There is not possible in Angular. (just boolean)
https://www.algolia.com/doc/api-reference/widgets/range-slider/angular/#widget-param-tooltips

**Describe the solution you'd like 🤔**

Add missing implementation. It should be relatively easy, because it is in js library. In my opinion it is basic functionality for every other slider and should be present in this lib.

It should be possible to create sometring like this:

![image](https://user-images.githubusercontent.com/18282249/108202201-0b289300-7121-11eb-9b49-6119ad627410.png)

**Describe alternatives you've considered ✨**

As an alternative is custom implementation that takes a long time.

**Additional context**

**Comment by Haroenv** [comment]
For the time being this would require a fork of https://github.com/algolia/angular-instantsearch/blob/v3/src/range-slider/range-slider.ts, but all code is in this one file to get it to work.

The relevant part that you'd need to change is:

https://github.com/algolia/angular-instantsearch/blob/v3/src/range-slider/range-slider.ts#L132

**Comment by Celtian** [comment]
@Haroenv I know where it is, but i do not know how to change it without forking easily. Forks cannot be used in our project because of maintenance.

**Comment by Haroenv** [comment]
Unfortunately I don't see an alternative for this situation today, sorry!

**Comment by Celtian** [comment]
I have find solution - inheritance. But you have mistake here https://www.algolia.com/doc/api-reference/widgets/range-slider/angular/#full-example it is not valid for v3. I spend few hours to find this problem.

**Comment by tkrugg** [comment]
Hi Celtian, could you clarify what isn't working, or what you had to fix for this to work?
