### ISSUE TITLE
Cannot read property 'removeWidget' of undefined  polyfills

### ISSUE THREAD

**Issue by nadhir-falta** [algolia/angular-instantsearch#809]
After upgrading to Angular 11 the search started acting weird when navigating away from the page.
I receive the following error:

```Cannot read property 'removeWidget' of undefined  polyfills```
Tried different versions of instantsearch but nothing worked. (Removing algolia completely worked though)

"algoliasearch": "^3.35.1",
"angular-instantsearch": "^3.0.0-beta.5",
"instantsearch.js": "^3.7.0",

I also tried compiling only to es5 still didn't work
I also tried disabling ivy
I tried adding this:
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default%2CArray.prototype.find%2CArray.prototype.includes%2CPromise%2CObject.assign%2CObject.entries"></script>

**Screenshots 🖥**
![image](https://user-images.githubusercontent.com/9285569/114914864-d8cda600-9df0-11eb-9ac2-8659faa3cf78.png)

**Environment:**

 - OS: android
 - Browser chrome
 - Version 75

**Comment by francoischalifour** [comment]
Hey! Thanks for reporting the issue.

Can you please share a reproduction in this [Angular InstantSearch](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/angular-instantsearch) sandbox with the dependencies that fail?

Thanks!
