### ISSUE TITLE
Remove CommonJS dependencies

### ISSUE THREAD

**Issue by jonhunter13** [algolia/angular-instantsearch#810]
Hello!

We are trying to trim our package size and found that the instantsearch.js has a lodash dependency. We just finished removing lodash from our application only to find it is included here. Please see this build warning: 

`Warning:  /frontendv2/node_modules/angular-instantsearch/node_modules/instantsearch.js/es/connectors/current-refined-values/connectCurrentRefinedValues.js depends on 'lodash/isString'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

As the link suggests, it's not recommended to use CommonJS dependencies. Can the team remove this dependency?

**Environment:**

 - Angular v11.2.7
 - Angular InstantSearch v2.3.0

**Comment by francoischalifour** [comment]
Lodash is used by the InstantSearch.js version that Angular InstantSearch 2 relies on. Angular InstantSearch v4 (currently in `alpha`), which is based on a newer InstantSearch.js version, does get rid of Lodash.

**Comment by rijkt** [comment]
After upgrading to angular-instantsearch@4.0.1 today, we still have the following warnings in our build:

> Warning: project/node_modules/instantsearch.js/es/lib/routers/history.js depends on 'qs'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
> 
> Warning: project/node_modules/instantsearch.js/es/lib/utils/renderTemplate.js depends on 'hogan.js'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
> 
> Warning: project/node_modules/instantsearch.js/es/widgets/index/index.js depends on 'algoliasearch-helper'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

While we don't have lodash anymore the Issue per the described in the title isn't fixed.

**Comment by Haroenv** [comment]
This is only a warning, not an error, no?

**Comment by rijkt** [comment]
Hey @Haroenv, that is correct. I think this would be a possible performance improvement, if the Angular message is to be trusted.

**Comment by Davste93** [comment]
Hey, could this be re-opened please, this would be a performance improvement

**Comment by Haroenv** [comment]
Sorry, the "performance improvement" message with relation to commonJS is specifically for libraries where not the whole exports are used. In this case all our dependencies are completely used, and thus wouldn't benefit from a performance improvement.
