### ISSUE TITLE
Library is preventing update to Angular 12 (requires <9.0.0) and by this, the upgrade of TypeScript

### ISSUE THREAD

**Issue by somehan** [algolia/angular-instantsearch#813]
**Describe the bug 🐛**

After upgrading to angular 12.0.1 npm tells us 
```npm WARN angular-instantsearch@3.0.0-beta.5 requires a peer of @angular/common@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself. ```

**To Reproduce 🔍**

1. Use "angular-instantsearch" in an angular project
2. Upgrade angular to v12
3. Run `npm i`

**Expected behavior 💭**

Npm to not complain about mismatches in peer dependencies.

**Environment:**

 - OS: Debian Linux

**Comment by shortcuts** [comment]
Hi there,

This warning is normal since the version installed on your side doesn't match our allowed version range.

You can bypass this warning by running `npm i --legacy-peer-deps` ([stackoverflow](https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh)) but this may create other conflicts due to potential breaking changes in the newer versions.

**Comment by somehan** [comment]
Thanks for your reply!

My suggestion is to make the library work with angular 12. 
Version 8 and lower are no longer under support: 
![image](https://user-images.githubusercontent.com/44295239/119611186-a608cb80-bdfa-11eb-85bf-787927f45f3d.png) (cf https://angular.io/guide/releases)

**Comment by shortcuts** [comment]
Thanks for the suggestion @somehan, this is not yet planned but we will make sure to consider it next quarter!

**Comment by somehan** [comment]
As of today we can't even update TypeScript in our web project any more: 
*  `angular-instantsearch ` prevents upgrading Angular
* The outdated version of Angular then prevents updating TypeScript

**Comment by shortcuts** [comment]
Hey @somehan, we will release an experimental update on Angular InstantSearch next week, which supports Angular 12 and also upgrades the TypeScript dependency.

Keep in mind that this is experimental, so any testing would help so we can improve our support of the newest versions!

**Comment by somehan** [comment]
@shortcuts I'm happy to help. Is there an update I could try?

**Comment by Haroenv** [comment]
It's slightly delayed, but you can build manually on the v4 branch @somehan :)

**Comment by somehan** [comment]
I was not able to build the library.

Will there be a release?

**Comment by shortcuts** [comment]
Hi @somehan, here's the open PR if you want to track the progress: https://github.com/algolia/angular-instantsearch/pull/818
