### ISSUE TITLE
One-to-One / One-to-Many Relationships

### ISSUE THREAD

**Issue by Karman40** [algolia/angular-instantsearch#814]
Does Algolia support in-document query? For example, I have a "users" table and an "address" table.
If you support it then, could you help, how is it possible to query this and how can this be solved under "refriments"?

I need One-to-One Relationships.

User Model:
```
{
    name: "salalsa",
    address: "01"
}
```
Address model:
```
{
    id: 01
    city: any
}
```

I want to result:
```
{
  name: "salalsa",
  address: {
     id: 01,
     ...
  }
}
```

Thanks for help!

**Comment by Haroenv** [comment]
more information can be found here: https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/prepare-data-in-depth/#handling-record-hierarchy

We recommend flattening the data before saving in Algolia, which will allow you to avoid complicated hierarchical queries

**Comment by Karman40** [comment]
@Haroenv 
I understand what you suggest but unfortunately this cannot be solved because both data are variable and this would make synchronization quite complicated.

I did not find on the attached page how to solve my question described above, could you help me where it is?

**Comment by Haroenv** [comment]
Sorry, I can only think of the documented way to deal with information organised this way. Algolia doesn't have relationships

**Comment by Karman40** [comment]
Then this is not a recommended solution, but only this is possible ...

Are there any plans for development this?

**Comment by Haroenv** [comment]
Not that I'm aware of, sorry! Since this issue is unrelated to angular, I'll close it now, but feel free to write an email to support@algolia.com for more guidance on how to implement the linked solution.

Have a great day!
