### ISSUE TITLE
I could not find what I was looking for

### ISSUE THREAD

**Issue by lmolteni** [algolia/angular-instantsearch#816]
Hi! I have a documentation issue on Angular-InstantSearch, I could not find what I was looking for which is: Implement Multi Index Search with Angular-InstantSearch library

**Comment by Haroenv** [comment]
In the current version of Angular InstantSearch, this isn't yet possible, but if you upgrade to v4 of Angular InstantSearch (currently in alpha), you can use the ais-index component to search through multiple indices at once

**Comment by tkrugg** [comment]
Just for the record, If you can't use the 4-alpha yet, you can try using `connectAutocomplete`. The solution is documented here https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/multi-index-search/angular/
