### ISSUE TITLE
Algolia + instantsearch doesn't work on IE11

### ISSUE THREAD

**Issue by asvitlica-vega** [algolia/angular-instantsearch#817]
## 🐛 Bug description

We've been experiencing bugs with instantsearch and Algolia integration in IE11. We checked the docs, tried out the official polyfil.io fix, but the problem persisted.

We get the following errors:
`Unable to get property 'add' of undefined or null reference`
`Unable to get property 'removeAllListeners' of undefined or null reference`

FYI Our app is written in Angular 11

## 🔍 Bug reproduction
Component initialization:
![algolia](https://user-images.githubusercontent.com/74365443/121894666-b2a88180-cd1f-11eb-8e8e-f720cd593846.PNG)

**Comment by eunjae-lee** [comment]
Hi @asvitlica-vega 
I believe this concerns "Angular InstantSearch", so I moved the ticket to this repository.
Could you provide us with a minimal reproduction so that we can take a look at your issue?
With the information given, it's hard for us to know.

**Comment by asvitlica-vega** [comment]
@eunjae-lee it is really hard to provide you with a small snippet, but I'll try.
Meanwhile, here's the exact line we're receiving an error from:
![removelisteners](https://user-images.githubusercontent.com/74365443/122000698-8b999080-cdaf-11eb-9a12-2c5a2065f9cf.PNG)

**Comment by Haroenv** [comment]
It seems like the index widget unmounts either before init was called or after it had already been removed. Are you really seeing this only on IE11? It seems unrelated to the browser

**Comment by asvitlica-vega** [comment]
> It seems like the index widget unmounts either before init was called or after it had already been removed. Are you really seeing this only on IE11? It seems unrelated to the browser

Yes, it only happens on IE11.
Library versions we use (maybe they are not compatible):
- "algoliasearch": "4.9.1",
- "angular-instantsearch": "3.0.0-beta.5",
- "instantsearch.js": "4.23.0"

**Comment by Haroenv** [comment]
Yes, that's true, InstantSearch.js should be <4, so InstantSearch@3.7.0

**Comment by asvitlica-vega** [comment]
Changing the version didn't work. We're dropping the feature for IE11.

**Comment by tkrugg** [comment]
Alright, I'll close this issue then. Feel free to reopen if any change on your side.
