### ISSUE TITLE
Angular-12

### ISSUE THREAD

**Issue by mohamednaleem** [algolia/angular-instantsearch#819]
Is the algoliasearch support for Angular version 12. I tried to import the components but getting an error.

**Comment by somehan** [comment]
cf https://github.com/algolia/angular-instantsearch/issues/813

**Comment by tkrugg** [comment]
Thank @mohamednaleem (and @somehan to pointing to the duplicate). We're actively working on the release of a compatible version for Angular 12: you can follow the PR here: #818
