### ISSUE TITLE
Can't perform facet count, as no facet is set

### ISSUE THREAD

**Issue by mohamednaleem** [algolia/angular-instantsearch#820]
Hi, 

When I tried to use ais-refinement-list in angular-12v I am getting the below error "Can't perform facet count, as no facet is set" even given the attribute name correctly.

<ais-instantsearch [config]="config">
    <ais-search-box></ais-search-box>
    <ais-refinement-list
  attribute="title"
  operator="or"
  [limit]="10"
>
</ais-refinement-list>
<ais-instantsearch [config]="config">

Please help me with how to solve this issue. Is this issue is for angular-12v

**Comment by Haroenv** [comment]
is the attribute "title" set up as `attributeForFaceting` in the dashboard?

**Comment by mohamednaleem** [comment]
Thanks for the reply, Actually I am using angular12 and not using the
Algolia dashboard instead am fetching the data from the strapi headless cms
database so using instantMeiliSearch

.html

<ais-instantsearch [config]="config">
    <ais-search-box></ais-search-box>
    <ais-refinement-list
  attribute="title"
>
</ais-refinement-list>

    <ais-hits>
      <ng-template let-hits="hits">
        <p-carousel class="mp-carousel-list mp-carousel-padding" [value]=
"hits"
        [showNavigators]="true" [responsiveOptions]="responsiveOptions"
[numVisible]="5"
        [numScroll]="5" [showIndicators]="false" [circular]="false">
        <ng-template let-hit pTemplate="item">
              <mat-card class="d-flex flex-column justify-content-between">

.ts file
 import { environment } from 'src/environments/environment';
import { instantMeiliSearch } from ***@***.***/instant-meilisearch';
import { Curatedpick } from '../models/curated-picks';


const searchClient = instantMeiliSearch(
  'http://localhost:7700',
  'fs83kjsfs038e2o3usflsjfslhs',
)

**Comment by Haroenv** [comment]
Sorry, we don't support instantMeiliSearch, you can open an issue on their repository

**Comment by Haroenv** [comment]
FYI, this is a known issue on instant-meilisearch: https://github.com/meilisearch/instant-meilisearch#3-emove-attributes-from-facet-list

**Comment by mohamednaleem** [comment]
Thanks Algolia/Angular-Instantsearch,

I am following this link. Please refer this and help me what can I do. Here
there is no any error.

https://codesandbox.io/s/im-angularis-7xipe?file=/src/app/app.component.ts:159-188
