### ISSUE TITLE
I could not find the number data type is not allowing to add into the attribute for faceting

### ISSUE THREAD

**Issue by mohamednaleem** [algolia/angular-instantsearch#823]
I try to add the rating field(number) into the facet but it is not adding. Only the string data type is adding.

http://localhost:7700/indexes/xxx/settings

{"rankingRules":["typo","words","proximity","attribute","wordsPosition","exactness"],"distinctAttribute":null,"searchableAttributes":["*"],"displayedAttributes":["*"],"stopWords":[],"synonyms":{},"attributesForFaceting":["title","company"]}

Please find the version.
{"commitSha":"UNKNOWN","buildDate":"2021-03-30T15:13:32.344119665+00:00","pkgVersion":"0.20.0"}

**Comment by Haroenv** [comment]
Sorry, but this question seems to be the same as #820, about MeiliSearch, please ask your questions in https://github.com/meilisearch/instant-meilisearch/issues, we are unrelated to Meili, so can not answer your questions that are related to it.
