### ISSUE TITLE
[bug] pagination - link stays in focus after it is clicked

### ISSUE THREAD

**Issue by MonteJagger** [algolia/angular-instantsearch#837]
**Describe the bug 🐛**
The issue occurs in the ais-pagination component.
When a user clicks on the button, what happens is that the button will stay on the focused state until the user clicks somewhere else.

**To Reproduce 🔍**

1. https://staging-public.flodogs.com/search?ab-forced=flo_14009_algolia_search-1
2. Scroll down to the pagination at the bottom

**Expected behavior 💭**

Since the state is stuck on focus, the expected behavior is that once the button is clicked, the button will be out of focus.

**Screenshots 🖥**
https://user-images.githubusercontent.com/7373171/135520700-5a19dcfd-7be7-45b8-8711-b248da2d7c9a.mov

**Additional context**
Preferably would like to automatically scroll to the top when a user clicks a different page link. This happens on mobile but not on web. Can this be included in the fix.

**Comment by sarahdayan** [comment]
Hey @MonteJagger!

The focus state is inherent to how the browser handles focus on clicked elements, it isn't linked to React InstantSearch or the `Pagination` widget.

When you press a link in the pagination, the link enters in `:focus` and `:active` state. As you release, the `:active` state goes away, but the link stays in focus. You can see an isolated example with a plain `<a>` element [here](https://codepen.io/sarahdayanalgolia/pen/WNOWwby).

If you want to have the button with the gray background only when the button is `:active` (that is, during `mousedown`), you should update your CSS to style the `:active` state, not the `:focus` one. **It's still highly recommended to style your `:focus` state**, for example with a visible outline.

Regarding the behavior of scrolling to the top of the page, you can achieve this with JavaScript using APIs like [`Window.scrollTo`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) or [`Element.scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).

**Comment by MonteJagger** [comment]
`When you press a link in the pagination, the link enters in :focus and :active state. As you release, the :active state goes away, but the link stays in focus. You can see an isolated example with a plain <a> element here.`

@sarahdayan and this is what we want to resolve in the ticket since this is not the expected behavior. We don't want the button to still be in the `:focus` state after being clicked. This is an issue because there is no`:hover` state unless the user clicks outside the button
[Example for expected behavior](https://codepen.io/humethazine/pen/LYLvRME)

**Comment by sarahdayan** [comment]
@MonteJagger Persisting the `:focus` state on click is a browser standard. However, the `:focus-visible` state only applies when an element matches the `:focus` state _and_ the user agent determines that the focus should be made evident on the element (more on this in the [spec](https://www.w3.org/TR/selectors-4/#the-focus-visible-pseudo)).

Instead of manually removing focus with JavaScript, you can update your CSS and apply styles to the `:focus-visible` pseudo-class instead of `:focus` ([example](https://codepen.io/sarahdayanalgolia/pen/eYRoBQN)).

**Comment by MonteJagger** [comment]
@sarahdayan this doesn't work since there is already styling for the `:focus` state in the pagination component that we can't access
<img width="1439" alt="Screen Shot 2021-10-01 at 1 07 07 PM" src="https://user-images.githubusercontent.com/7373171/135667456-9409a606-cbf0-4ac1-8d70-c05500767b50.png">

You can take a look at our app here if you scroll down
https://www.flowrestling.org/search?ab-forced=flo_14009_algolia_search-1

**Comment by sarahdayan** [comment]
@MonteJagger You can undo these styles in your CSS code, like this:

```css
/**
 * This sets the :focus styles to be the same as the default ones
 */
.ais-Pagination-link:focus {
  color: #fff;
  background-color: #ff140f;
}

/**
 * This sets a visual indicator when the element is focused, for accessibility purposes
 * Change this to whatever makes sense for your site
 */
.ais-Pagination-link:focus-visible {
  outline: 1px dotted gray;
}
```

I've opened an [issue](https://github.com/algolia/instantsearch-specs/issues/118) so we update this in our theme.

**Comment by MonteJagger** [comment]
@sarahdayan I'll also add that the issue happens on Chrome. Tried on safari and it works as expected
