### ISSUE TITLE
Feature Request - Ability to prevent search on init

### ISSUE THREAD

**Issue by brianpooe** [algolia/angular-instantsearch#883]
Algolia fires a search on an empty query on app load. Is there a way to prevent this?

**Comment by Haroenv** [comment]
There's a guide around preventing search requests here: https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/angular/. Does that help you?

**Comment by brianpooe** [comment]
@Haroenv thanks that helped.
