### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by Haroenv** [algolia/angular-instantsearch#885]
**Is your feature request related to a problem? Please describe 🙏**

According to the peer dependencies and tests we don't support Angular 13, but most likely we *do* support it.

**Describe the solution you'd like 🤔**

Check https://angular.io/guide/update-to-latest-version and update the peer dependency

**Describe alternatives you've considered ✨**

Nothing?

**Comment by Haroenv** [comment]
Sorry, no progress has been made on this topic yet, however if you have interest and know-how in fixing this, we'd gladly test out a pull requests that changes the peer dependencies and makes the required changes @SvetlanaMuravlova

**Comment by mwawrusch** [comment]
This is really annoying. instead of easily upgrading now development is blocked, which obviously costs us money in lost dev hours. And it's been going on with quite a few service providers.

**Comment by mwawrusch** [comment]
Also, it is not our job to do your work. We all have enough on our hands getting our own products out.

**Comment by SvetlanaMuravlova** [comment]
@Haroenv does it mean you aren't going to support angular since 13 version?

**Comment by Haroenv** [comment]
version 4.1.0 supports Angular 13 now. Sorry for the wrong impression my earlier comment caused; we didn't plan doing this immediately as we didn't get any other customer feedback about this before today.

Hope you all have a great time implementing Angular InstantSearch and Algolia in general!
