### ISSUE TITLE
Guide: How to dynamically update the search parameters

### ISSUE THREAD

**Issue by iam4x** [algolia/angular-instantsearch#92]
This question was asked through support, it's not doable easily for now.

**Comment by Haroenv** [comment]
I wonder if you could have a custom widget, mount it and change the instance's helper's parameters in setInterval?

**Comment by vvo** [comment]
Why the need for a setInterval?

What about the use of the use of the Configure widget? Shouldn't it be the solution to this

**Comment by Haroenv** [comment]
I thought this said periodically :)

**Comment by samouss** [comment]
What about a `Configure` widget?

**Comment by Haroenv** [comment]
Configure will be best indeed! I don’t think widgets (in lieu of connectors) is handled in angular InstantSearch yet though

**Comment by samouss** [comment]
That's why maybe it would have been interesting to implement it as a connector. At some point we may plan to ship the connectors as an external package. If we do so we should have a connector for every widget implemented. Or allow the integration of widget in the libraries that implement the connectors, but it seems a bit strange.

cc @bobylito

**Comment by vvo** [comment]
> If we do so we should have a connector for every widget implemented

THis is normally the API contract we imagined initially yes. One widget one connector BUT if two widgets are based on the exact same connector.

**Comment by bobylito** [comment]
> That's why maybe it would have been interesting to implement it as a connector. At some point we may plan to ship the connectors as an external package. If we do so we should have a connector for every widget implemented. Or allow the integration of widget in the libraries that implement the connectors, but it seems a bit strange.

But since it's a headless widget. We chose the widget format, because there is no rendering hence providing a rendering function will feel weird too.

**Comment by samouss** [comment]
Yep but how we gonna integrate it with Angular or Vue since there is no connector? Each lib will implement their own logic of the widget?

**Comment by bobylito** [comment]
You can use the widget directly. Haroen is doing that with vue actually.

**Comment by iam4x** [comment]
The `<ais-configure>` widget is listening on `searchParameters` changes and will update them dynamically by triggering a new search 👍

**Comment by vvo** [comment]
Great! gg

**Comment by tahminabs23** [comment]
I am using <ais-configure [searchParameters]="{ aroundLatLng: '0, 0' }"></ais-configure>, and dynamically updating the { aroundLatLng: '0, 0' } object based on user's input, but I can not see any change in search result. Can anyone tell me what I missed here?

**Comment by tahminabs23** [comment]
@Haroenv or @iam4x or anyone, would you please help me to find out what's wrong I am doing here?

**Comment by bobylito** [comment]
@tahminabs23 Thanks for the example. That's super helpful. Unfortunately this won't work as the values of `searchParameters` are not watched.

They only way I see that you can make that work is by using the configure widget and update its value dynamically. https://community.algolia.com/angular-instantsearch/widgets/configure.html

**Comment by tahminabs23** [comment]
@bobylito Thank you so much for responding. If I understand you correctly, do you want me to use my algolia credential in configure widget? If that, then I have updated the code with configure widget. 

Actually, my requirement is to update the search result dynamically. I am working in an ionic app, and when a user will change its location, that time I need to track that event and update the search result based on current location to populate nearby results.

Can you please tell me how can I make this `searchParameters` change effective on the search result?

Thank you once again.

**Comment by Haroenv** [comment]
Using the configure widget is the way to go, that one listens to changes in the search parameters

**Comment by tahminabs23** [comment]
@Haroenv I am using 'configure' widget, but you see @bobylito said, "Unfortunately this won't work as the values of `searchParameters` are not watched." Then what is the correct way to do this?

**Comment by Haroenv** [comment]
Open a new issue please, it’s getting confusing with this old issue through it
