### ISSUE TITLE
Use yarn workspaces

### ISSUE THREAD

**Issue by iam4x** [algolia/angular-instantsearch#95]
In order to resolve dependencies issues we should use yarn workspaces for building examples & documentation.

cc @vvo

**Comment by Haroenv** [comment]
This should be as simple as adding `"workspaces": ["community-website", "src", "examples/*"]`, moving the main package into a subfolder (I called it src in this example), and putting private: true on the root package.json. You also need to remove the yarn.lock from all but the root after running `yarn` once :)

**Comment by iam4x** [comment]
https://github.com/angular/angular-cli/issues/7097

Angular CLI cannot resolve node_modules from a parent folder, this won't be doable for now. I will give it another try when Angular CLI v6 is out.

**Comment by Haroenv** [comment]
You can use nohoist to fix this: https://yarnpkg.com/blog/2018/02/15/nohoist/

**Comment by iam4x** [comment]
@Haroenv Yes sure, but there is no point to flag as nohoist all the examples dependencies since I wanted to have workspaces to share theses redundant dependencies :(
