### ISSUE TITLE
Support Angular 14

### ISSUE THREAD

**Issue by Karman40** [algolia/angular-instantsearch#954]
**Is your feature request related to a problem? Please describe 🙏**

According to the peer dependencies and tests we don't support Angular 14, but most likely we do support it.

**Describe the solution you'd like 🤔**

Check https://angular.io/guide/update-to-latest-version and update the peer dependency

**Comment by Haroenv** [comment]
If you update with the peer dependency warning ignored, is there any further errors you see indicated?

**Comment by dhayab** [comment]
@Haroenv I just performed an update on a `create-instantsearch-app` template and it works without any additional warnings or issues.

**Comment by dhayab** [comment]
Hi @Karman40, we just released [Angular InstantSearch v4.2.1](https://github.com/algolia/angular-instantsearch/releases/tag/4.2.1) which updates the peer dependencies range for Angular.

**Comment by Karman40** [comment]
@Haroenv, @dhayab sorry for the late answer. I quickly tried the app and I didn't have any bugs. Thanks a lot!!
