### ISSUE TITLE
request.query type Error in angular 

### ISSUE THREAD

**Issue by dmsammusic** [algolia/angular-instantsearch#965]
**Describe the bug 🐛**

When i try to set No result message with {{results.query}} . it throws error. 

**To Reproduce 🔍**

in this example... 
https://github.com/algolia/doc-code-samples/tree/master/angular-instantsearch/extending-widgets

When i try to add {{results.query }}it throws a error in browser console. 
if i use {{results }} or remove that results variable it works.
How to handle No results found with input data.
and  I need to show the results when the user start to type in searchBox.
but as of now, 
it shows results all time. or No result Found all time. How can i handle this. 

and How it will works on SPA. i place a searchbox in navbar.
if i click another tab after something searched. the results should be hide.. but now it Overlay above all tabs

**Expected behavior 💭**

 I expecting two things.
 1) the search results only show when i start type in the search box.
 2) No results Found {{ result.query }} this message should show with input data.

**Screenshots 🖥**
this is my code.
![Screenshot from 2022-09-14 14-27-19](https://user-images.githubusercontent.com/96620534/190109752-a35a6b57-5b25-4d39-91ac-843e76c5552a.png)

this is the error
![Screenshot from 2022-09-14 14-29-15](https://user-images.githubusercontent.com/96620534/190110228-db39fd8c-3bdc-4e30-b522-a33f254c797d.png)

**Environment:**

 - OS: Ubuntu 22.04
 - Browser : [ Firefox]

**Additional context**

could u provide latest working Examples for angular-InstantSearch will helpful. or Update the older examples to the latest V4 version.

**Comment by Haroenv** [comment]
You need to put that in the `*ngIf="results"`, as there's an initial state where the template renders before the first search request is done

**Comment by dmsammusic** [comment]
could u explain with a example. or codesandbox code

**Comment by Haroenv** [comment]
```html
<ais-hits>
  <ng-template let-hits="hits" let-results="results">
    <div *ngIf="hits. length === 0 && results">
      No results have been found for {{ results. query }}.
    </div>
    <ol class="ais-Hits-list" *ngIf="results">
      <li class="ais-Hits-item" *ngFor="let hit of hits">
        <article>...</article>
      </li>
    </ol>
  </ng-template>
</ais-hits>
```

**Comment by dmsammusic** [comment]
yes That works for that example.. Could u help me on one more thing.. how to search by every letter typed..

**Comment by Haroenv** [comment]
That's the default @dmsammusic, are you using the default search-box? is `search-as-you-type` disabled by any chance?

**Comment by dmsammusic** [comment]
Yes I am Using Default search Box.. but In default searchBox, the results always Showing.. but i dont need like that when the user type in search the results need to show.

will look at this "search-as-you-type"

**Comment by Haroenv** [comment]
I'll close this issue now, as the original question is handled

**Comment by dmsammusic** [comment]
Could u say how to hide the results showing all time.

**Comment by dmsammusic** [comment]
and pagination and stat also.. if i put that component it shows the results.
`<ais-hits>
  <ng-template let-hits="hits" let-results="results">
    <div *ngIf="hits. length === 0 && results">
      No results have been found for {{ results.query }}.
    </div>
    <ol class="ais-Hits-list" *ngIf="results"*>
      <li class="ais-Hits-item" *ngFor="let hit of hits">
        <article>...</article>
      </li>
    </ol>
  </ng-template>
</ais-hits>`

in the Above Code i added  *ngIf="results" but i think this is also not working. 
why this happens is there any way.  i dont found any clear documents regarding this.
