### ISSUE TITLE
I was trying to replicate the refinement-list but cannot find ais-facets-search

### ISSUE THREAD

**Issue by hsnassaad** [algolia/angular-instantsearch#966]
**Describe the bug 🐛**
I want to replicate the `refinement-list` component to allow users to select multiple items, because now if we enable the search inside the `RefinementList` and tried to search for an item and then select that item the list reset the search inside the  RefinementList causing all the highlights and the search itself to be reseted, so i wanted to implement my own logic.

So i went to the repo where the [refinement-list](https://github.com/algolia/angular-instantsearch/blob/9599f27fbc13229fa52863eaf2359da5e9fece86/src/refinement-list/refinement-list.ts) code, and copied the html template code, but then i got an error on my angular project saying that `ais-facets-search` is not a known element.

And after invetigation i found that in the `NgAisRefinementListModule` the `NgAisFacetsSearch` is not exported and i guess that what is causing the problem.

Please advise what can i do, because we need `NgAisFacetsSearch` in order to call the search method inside the refinement-list

**Environment:**

 - OS: mac
 - Browser chrome
 - Version 12.6

**Comment by Haroenv** [comment]
As you likely will want to modify it, you can use https://github.com/algolia/angular-instantsearch/blob/master/src/refinement-list/facets-search.ts as a base, and make your changes, does that make sense?

**Comment by hsnassaad** [comment]
Yay that workss, thanks so much
