### ISSUE TITLE
ais-panel doesn't hide when ais-refinement-list is empty

### ISSUE THREAD

**Issue by nacoleman** [algolia/angular-instantsearch#974]
According to the documentation (https://www.algolia.com/doc/api-reference/widgets/panel/angular/): 

"The panel widget wraps other widgets in a consistent panel design. It also reacts by adding a CSS class when the widget no longer can refine, for example, when a [refinementList](https://www.algolia.com/doc/api-reference/widgets/refinement-list/angular/) becomes empty because of the current search results."

However I am using the panel like this and no classes are added and nothing is hidden?

```
 <ais-panel header="Class">
    <ais-refinement-list [autoHideContainer]="true" attribute="class" [limit]="10" [sortBy]="['name:asc']">
    </ais-refinement-list>
  </ais-panel>

```
You can see it here

https://www.ultraislife.com/uniqs/marketplace?uniqs%5BrefinementList%5D%5Bcollection%5D%5B0%5D=Elarium%20Keycards

Am I missing something?

**Comment by Haroenv** [comment]
Sorry, that part of the documentation is wrong, the panel in Angular InstantSearch doesn't have the feature of hiding when it's empty, but in your case you can use CSS anyway:

```css
.ais-Panel:has(ais-refinement-list:empty) {
    display: none;
}
```

I'll update the docs to remove that wrongly advertised feature

**Comment by nacoleman** [comment]
Ah ok thanks - yeah i just dug into the source code and can see its not there... thanks for the quick reply. Css works perfectly.

**Comment by Haroenv** [comment]
Perfect, it's removed from the docs now as well, thanks for opening this issue!
