### ISSUE TITLE
Pagination `pagesArray` is calculated every time whether it's used or not, making arrays of thousands of elements

### ISSUE THREAD

**Issue by flevi29** [algolia/angular-instantsearch#977]
**Describe the bug 🐛**

https://github.com/algolia/angular-instantsearch/blob/1a12f5ed0f2ef76f743d2b6f0790680252b368e9/src/pagination/pagination.ts#L142-L147

The above code, as far as I could tell while debugging, always executes, unconditionally. This means if there are 28000 pages, it will create a range array of 28000 numbers. Also it is a weird looking range implementation, while there is already a range method imported from `utils.ts`. The reason for it being a special range, is that it is called in a deferred manner? Doesn't seem like it works that way. Then why not just use an arrow function for it?

```typescript
const getPagesArray = () => range({ end: nbPages });
```

And then call it later when needed.

**To Reproduce 🔍**

N/A

**Expected behavior 💭**

`pagesArray` is calculated only when it's required.

**Screenshots 🖥**

N/A

**Environment:**

 - OS: Windows 11
 - Browser: Firefox 
 - Version: 106.0.5 (64-bit)

**Additional context**

N/A

**Comment by Haroenv** [comment]
There's indeed no reason for this, pages are already calculated in the connector now, so this work is done double. Would you be interested in making a pr using the `pages` array already created (doc: https://www.algolia.com/doc/api-reference/widgets/pagination/js/#connector-param-render-pages)?

**Comment by flevi29** [comment]
Sure, I'll give it a shot.

**Comment by Haroenv** [comment]
4.3.2. is now released with your optimisation, thanks again!
