### ISSUE TITLE
Disable widget while fetching Algolia keys?

### ISSUE THREAD

**Issue by shrestaz** [algolia/angular-instantsearch#98]
When instantsearch widget is initialized on the template with `<ng-ais-instantsearch [config]="algoliaEnv">`, it expects to connect with Algolia instantly, whereas realistically, it take a few seconds (~5 seconds at most) for the application to fetch API keys on the first run.

Is there a proper approach to disable search widget while it fetches the API key? My current _planned hack_ is to use `ngIf` to check if the application already has the keys and if not, display ***Search is indexing*** or something around that.
 
Thank you.
Manish

**Comment by Haroenv** [comment]
What do you not like about that "hack"? It doesn't seem like a bad solution to me

**Comment by shrestaz** [comment]
@Haroenv There's nothing wrong with it. I was just hoping if there was some method which would handle this more elegantly. Please go ahead and close the issue if there is no such method or other any other approach built in.
Thanks.

**Comment by Haroenv** [comment]
What I'm wondering is how come it takes five seconds before an API key can be given. What kind of flow do you have for that?

**Comment by shrestaz** [comment]
I have a Firebase function in the Angular project which fetches the Algolia key and saves it as a property of user in the Firestore, if it does not already exist. This process takes 3-5 seconds.

**Comment by Haroenv** [comment]
I think for now, whatever we could do internally in the library would have the same effect as an ngIf. Thanks for raising this issue, and let us know if you have other issues with this.
