### ISSUE TITLE
SSR example doesn't work

### ISSUE THREAD

**Issue by ohryk-intellias** [algolia/angular-instantsearch#990]
**Describe the bug 🐛**

The SSR example for the latest release (tag 4.4.0) doesn't work.

**To Reproduce 🔍**

1. Run `git clone https://github.com/algolia/angular-instantsearch.git`
2. Run `git checkout 4.4.0`
3. Run `yarn examples:ssr`
4. Disable JavaScript for the http://localhost:4000/
5. Open http://localhost:4000/?instant_search%5Bquery%5D=amazon

**Expected behavior 💭**

The rendered HTML page should display the search results. No errors in the server console output.

**Environment:**

 - OS: macOS 13.2.1
 - Browser: Chrome
 - Version 112.0.5615.49
 - Node: v14.21.3

**Additional context**

Seems that `ais-search-box` is not SSR-friendly and uses some browser-specific API. I tried to remove the `ais-search-box` widget and if so - then I can see the rendered page but when trying to change the query param in the URL - the same result appears.
<img width="1267" alt="Screenshot 2023-04-06 at 15 28 59" src="https://user-images.githubusercontent.com/64080949/230379462-0569adf8-657b-4c93-953f-d77ef94e0a66.png">

<img width="1271" alt="Screenshot 2023-04-06 at 15 29 13" src="https://user-images.githubusercontent.com/64080949/230379534-9672d571-d6a2-4885-8236-0ac806c60a27.png">

**Comment by aymeric-giraudet** [comment]
Hi @ohryk-intellias !

This is was actually fixed in #986, I will plan a `4.4.1` release and update this issue

**Comment by aymeric-giraudet** [comment]
Hey @ohryk-intellias, `4.4.1` has been released and it fixes this issue : 
<img width="1691" alt="image" src="https://user-images.githubusercontent.com/9158954/230435983-f69bf427-2348-49b6-9311-fd1f80df79c9.png">

Thanks again for your feedback 🙇
